function save_data_air(Rmtx,Lmtx,Cmtx, Rself,Lself, Rg,Lg,Pg, Rgself,Lgself, ...
    Rdc_fit, Ldc_fit, Rfit, Lfit,  ...
    pt_start, pt_end, dv, re, shape, dim1, dim2, len, R_pul, sig, mur, epr, ...
    grp_id, grp_type, pt_2d, ...
    bran_name, nod_start, nod_end, nod_name, nod_sr, nod_gnd,  bran_out, nod_out, ...
    soil_sig, gnd_off, frq, frq_cut,Nfrq, Nfit, dl, fpath, fname)

if ~isempty(fpath) || ~exist(fpath,'dir')==0
   fpath = [];
end

sname = [fpath, fname];

save(sname, 'Rmtx','Lmtx','Cmtx','Rself','Lself', 'Rg','Lg','Pg','Rgself','Lgself', ...
    'Rdc_fit', 'Ldc_fit', 'Rfit', 'Lfit',  ...
    'pt_start', 'pt_end', 'dv', 're', 'shape', 'dim1', 'dim2', 'len', ...
    'R_pul', 'sig', 'mur',  'epr', ...
    'grp_id', 'grp_type', 'pt_2d', ...
    'bran_name', 'nod_start', 'nod_end', 'nod_name', 'nod_sr', 'nod_gnd', 'bran_out', 'nod_out', ...
     'soil_sig', 'gnd_off', 'frq','frq_cut','Nfrq', 'Nfit', 'dl', ...
    'fpath','fname');


end
