function save_data_grid(Rgrid,Lgrid,Pgrid, Ygrid, Rs_grid,Ls_grid, ...
    Rdc_fit_grid, Ldc_fit_grid, Rfit_grid, Lfit_grid, ...
    Dfit_grid,Efit_grid,Rfit3_grid,Pfit3_grid, ...
    pt_start_grid, pt_end_grid, dv_grid, re_grid, ...
    shape_grid, dim1_grid, dim2_grid, len_grid, ...
    R_pul_grid, sig_grid, mur_grid, ...
    bran_name_grid, nod_start_grid, nod_end_grid, nod_grid_name, ...
    bran_out_grid, nod_out_grid, ...
    soil_sig, soil_epr, frq_cut,Nfrq,dl_grid, Nfit_grid, frq_grid, ...
    fpath_grid, fname_grid)

sname = [fpath_grid, fname_grid,'_grid'];

save(sname,  'Rgrid','Lgrid','Pgrid', 'Ygrid', 'Rs_grid','Ls_grid', ...
    'Rdc_fit_grid', 'Ldc_fit_grid', 'Rfit_grid', 'Lfit_grid', ...
    'Dfit_grid','Efit_grid','Rfit3_grid','Pfit3_grid', ...
    'pt_start_grid', 'pt_end_grid', 'dv_grid', 're_grid', ...
    'shape_grid', 'dim1_grid', 'dim2_grid', 'len_grid', ...
    'R_pul_grid', 'sig_grid', 'mur_grid', ...
    'bran_name_grid', 'nod_start_grid', 'nod_end_grid', 'nod_grid_name', ...
    'bran_out_grid', 'nod_out_grid', ...
    'soil_sig', 'soil_epr', 'frq_cut','Nfrq','dl_grid', 'Nfit_grid', 'frq_grid', ...
    'fpath_grid', 'fname_grid');

end
