function spice_double_exp_source(sr_type, sr_amp, sr_tau1, sr_tau2, td, ...
    fpath, fname)

% td - (s)

if sr_type == 0   % current source
    %% Write the Head of Circuit Network
    fid = fopen([fpath, '\', fname,'.cir'],'w+');
    
    fprintf(fid,'.SUBCKT %s iSR+ iSR- PARAMS: Amp=%.4f \n', fname, sr_amp);
    fprintf(fid,'************************************** \n');
    fprintf(fid,'*   Double Exponential Source MODEL  * \n');
    fprintf(fid,'*      Generated by Chen Hongcai     * \n');
    fprintf(fid,'*   Hong Kong Polytechic University  * \n');
    fprintf(fid,'*         All Rights Reserved        * \n');
    fprintf(fid,'************************************** \n');
    fprintf(fid,'* Model generated on %s \n',datestr(now,1));
    fprintf(fid,'* MODEL FORMAT: PSpice \n');
    fprintf(fid,'* node:  iSR+    iSR-  \n');
    
    fprintf(fid,'I_I1  iSR+  NR  DC 0Adc AC 0Aac \n');
    if sr_tau2<1e-3
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4fu \n', td*1e6, sr_tau2*1e6);
    else
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4f \n', td*1e6, sr_tau2);
    end
    
    fprintf(fid,'I_I2  NR  iSR+ DC 0Adc AC 0Aac \n');
    if sr_tau1<1e-3
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4fu \n', td*1e6, sr_tau1*1e6);
    else
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4f \n', td*1e6, sr_tau1);
    end
    fprintf(fid,'R_R1  NR iSR-  1u TC=0,0 \n');
    
    fprintf(fid,'.ENDS %s \n', fname);
    
    fclose(fid);
    
elseif sr_type == 1
    %% Write the Head of Circuit Network
    fid = fopen([fpath, '\', fname,'.cir'],'w+');
    
    fprintf(fid,'.SUBCKT %s vSR+ vSR- PARAMS: Amp=%.4f \n', fname, sr_amp);
    fprintf(fid,'************************************** \n');
    fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
    fprintf(fid,'*   Hong Kong Polytechic University  * \n');
    fprintf(fid,'*         All Rights Reserved        * \n');
    fprintf(fid,'************************************** \n');
    fprintf(fid,'* Double Exponential Source MODEL  \n');
    fprintf(fid,'* Model generated on %s \n',datestr(now,1));
    fprintf(fid,'* MODEL FORMAT: PSpice \n');
    fprintf(fid,'* node:  vSR+    vSR-  \n');
    
    fprintf(fid,'V_V1  NR  NVseries  \n');
    if abs(sr_beta)<1e-3
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4uf \n', td*1e6, sr_tau2*1e6);
    else
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4f \n', td*1e6, sr_tau2);
    end
    
    fprintf(fid,'V_V2  vSR+  NVseries  \n');
    if abs(sr_tau1)<1e-3
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4uf \n', td*1e6, sr_tau1*1e6);
    else
        fprintf(fid,'+EXP 0 {Amp} %.4fu %.4f \n', td*1e6, sr_tau1);
    end
    fprintf(fid,'R_R1  NR  vSR-  1u TC=0,0  \n');
    
    fprintf(fid,'.ENDS %s \n', fname);
    
    fclose(fid);
end



end
