function spice_surge_generator(Uc, Cs, Ls, Re, Rs1, Rs2, dir, fname)


fid = fopen([dir, '\', fname, '.cir'],'w+');

%% Write the Head of Circuit Network

fprintf(fid,'.SUBCKT %s gSR+ gSR- PARAMS: Uc=%.4f \n', fname, Uc);

fprintf(fid,'************************************** \n');
fprintf(fid,'*        Surge Generator MODEL       * \n');
fprintf(fid,'*      Generated by Chen Hongcai     * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');
fprintf(fid,'* node:  gSR+    gSR-  \n');


fprintf(fid,'C_Cs         gSR- N_Cs  %.4fu IC={Uc} TC=0,0 \n',Cs*1e6);
fprintf(fid,'X_S1         N_Cs N_S1 Sw_tClose  \n');
fprintf(fid,'+  PARAMS: tClose=0 ttran=1u Rclosed=0.01 Ropen=1Meg \n');

fprintf(fid,'R_RE         gSR- N_S1  %.4f  TC=0,0 \n',Re);

fprintf(fid,'R_Rs1        N_S1 N_Rs1  %.4f TC=0,0 \n',Rs1);
fprintf(fid,'L_Ls         N_Rs1 gSR+  %.4fu  \n',Ls*1e6);

fprintf(fid,'R_Rs2        gSR- gSR+  %.4f TC=0,0 \n', Rs2);

fprintf(fid,'.ENDS %s \n',fname);
fclose(fid);



end


