function spice_induced_v_fun(sr_type, sr_amp, sr_tau1, sr_tau2, n, ...
    fpath, fname)

if sr_type == 0   % current source
    %% Write the Head of Circuit Network
    fid = fopen([fpath, '\', fname,'.cir'],'w+');
    
    fprintf(fid,'.SUBCKT %s iSR+ iSR- PARAMS: Amp=%.2f n=%d \n', fname, sr_amp, n);
    fprintf(fid,'************************************** \n');
    fprintf(fid,'*         Heidler Source MODEL       * \n');
    fprintf(fid,'*      Generated by Chen Hongcai     * \n');
    fprintf(fid,'*   Hong Kong Polytechic University  * \n');
    fprintf(fid,'*         All Rights Reserved        * \n');
    fprintf(fid,'************************************** \n');
    fprintf(fid,'* Model generated on %s \n',datestr(now,1));
    fprintf(fid,'* MODEL FORMAT: PSpice \n');
    fprintf(fid,'* node:  iSR+  iSR- \n');
    
%     fprintf(fid,'E_ABM1  NAmp  0 \n');
%     fprintf(fid,'+VALUE { EXP( -%.2fu/%.2fu*PWRS(n*%.2fu/%.2fu,1/(n+1)) ) } \n', ...
%         sr_tau1, sr_tau2, sr_tau2, sr_tau1);
%     
%     fprintf(fid,'G_ABMI2  iSR+  0 \n');
%     fprintf(fid,'+VALUE { Amp/V(NAmp)*PWRS(TIME/%.2fu,n)/(1+PWRS(TIME/%.2fu,n))*EXP(-TIME/%.2fu) } \n', ...
%         sr_tau1, sr_tau1, sr_tau2);
    
    fprintf(fid,'G_ABMI2  iSR+  iSR- \n');
    fprintf(fid,'+VALUE { Amp*PWRS(TIME/%.4fu,n)/(1+PWRS(TIME/%.4fu,n))*EXP(-TIME/%.4fu) } \n', ...
        sr_tau1, sr_tau1, sr_tau2);

    fprintf(fid,'.ENDS %s \n', fname);
    
    fclose(fid);
    
elseif sr_type == 1
    %% Write the Head of Circuit Network
    fid = fopen([fpath, '\', fname,'.cir'],'w+');
    
    fprintf(fid,'.SUBCKT %s vSR+ vSR- PARAMS: Amp=%.2f n=%d \n', fname, sr_amp, n);
    fprintf(fid,'************************************** \n');
    fprintf(fid,'*         Heidler Source MODEL       * \n');
    fprintf(fid,'*      Generated by Chen Hongcai     * \n');
    fprintf(fid,'*   Hong Kong Polytechic University  * \n');
    fprintf(fid,'*         All Rights Reserved        * \n');
    fprintf(fid,'************************************** \n');
    fprintf(fid,'* Model generated on %s \n',datestr(now,1));
    fprintf(fid,'* MODEL FORMAT: PSpice \n');
    fprintf(fid,'* node:  vSR+ \n');
    
    fprintf(fid,'E_ABM1  vSR+  vSR- \n');
     fprintf(fid,'+VALUE { Amp*PWRS(TIME/%.4fu,n)/(1+PWRS(TIME/%.4fu,n))*EXP(-TIME/%.4fu) } \n', ...
        sr_tau1, sr_tau1, sr_tau2);
    
    fprintf(fid,'.ENDS %s \n', fname);
    
    fclose(fid);
end



end

