function spice_user_define_source(t, Isr, pathname, fname)

%% writing stimulus file
dt = t(2)-t(1);

fid = fopen([pathname,'\',fname,'.stl'],'w+');

fprintf(fid,'************************************** \n');
fprintf(fid,'*       User Defined Source Model    * \n');
fprintf(fid,'*       Generated by Chen Hongcai    * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1)); 
fprintf(fid,'* MODEL FORMAT: PSPICE Stimulus Data File\n');

fprintf(fid,';!Stimulus Get\n');
fprintf(fid,';! %s Analog\n',fname);
fprintf(fid,';!Ok\n');
fprintf(fid,';!Plot Axis_Settings\n');
fprintf(fid,';!Xrange 0 200us\n');
fprintf(fid,';!Yrange 0 1000\n');
fprintf(fid,';!AutoUniverse\n');
fprintf(fid,';!XminRes %fns\n',dt*1e9);
fprintf(fid,';!YminRes 0.1\n');
fprintf(fid,';!Ok\n');

fprintf(fid,'.STIMULUS %s PWL\n',fname);
fprintf(fid,'+ TIME_SCALE_FACTOR = 1u\n');
fprintf(fid,'+ VALUE_SCALE_FACTOR = 1\n');

Npt = length(t);
for ik = 1:Npt
    fprintf(fid,'+   ( %.6e, %.6e )\n',t(ik)*1e6,Isr(ik));
end

fclose(fid);

end


