function Ls = induct_bar_Hoer(a, b, l)
%  Function:       induct_bar_Hoer
%  Description:    Calculate DC inductance of the rectangle conductor using
%                  exact integral formula.
%
%  Calls:          
%
%  Input:          a       --  width of conductors (N*1) (m)
%                  b       --  thick of conductors (N*1) (m)
%                  l       --  length of conductors (N*1)
%  Output:         Ls    --  Ls vector (have multiplied length)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2015-02-16

mu0 = 4*pi*1e-7;

abl = a.*b.*l;

a2 = a.^2;
b2 = b.^2;
l2 = l.^2;

a4 = a2.^2;
b4 = b2.^2;
l4 = l2.^2;

Dabl = sqrt(a2+b2+l2);
Dab = sqrt(a2+b2);
Dal = sqrt(a2+l2);
Dbl = sqrt(b2+l2);


% include self internal inductance
Ls = mu0./(120*pi.*a2.*b2).*( ...
4*(a.^5+b.^5+l.^5) ...
- 4*(a4-3*a2.*b2+b4).*Dab ...
- 4*(a4-3*a2.*l2+l4).*Dal ...
- 4*(b4-3*b2.*l2+l4).*Dbl ...
+ 4*(a4+b4+l4-3*a2.*b2-3*a2.*l2-3*b2.*l2).*Dabl ...
- 40.*abl.*( ...
a2.*atan((b.*l)./(a.*Dabl)) ...
+b2.*atan((a.*l)./(b.*Dabl)) ...
+l2.*atan((a.*b)./(l.*Dabl)) ...
) ...
+ 30.*abl.*( ...
a.*b.*log((l+Dabl)./(-l+Dabl)) ...
+a.*l.*log((b+Dabl)./(-b+Dabl)) ...
+b.*l.*log((a+Dabl)./(-a+Dabl)) ...
) ...
-5*a.*( b4.*log( ((-a+Dab).*(a+Dabl))./((a+Dab).*(-a+Dabl)) ) + l4.*log( ((-a+Dal).*(a+Dabl))./((a+Dal).*(-a+Dabl)) ) ) ...
-5*b.*( a4.*log( ((-b+Dab).*(b+Dabl))./((b+Dab).*(-b+Dabl)) ) + l4.*log( ((-b+Dbl).*(b+Dabl))./((b+Dbl).*(-b+Dabl)) ) ) ...
-5*l.*( a4.*log( ((-l+Dal).*(l+Dabl))./((l+Dal).*(-l+Dabl)) ) + b4.*log( ((-l+Dbl).*(l+Dabl))./((l+Dbl).*(-l+Dabl)) ) ) ...
);


end

