%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%  purpose: this is a demo code to load & show the binary snpashot data file generated by
%%%%  the WCT GUI
%%%%
%%%%  copyright:   wave computation technology
%%%%  Author:      mengqing yuan
%%%%  contact:     mqyuan@wavenology.com
%%%%  date:        03/28/2016
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [snapFun] = fdtd_read_snapshot(fname, mask_for_case)

snapFun = [];
%% define number of the field components
% firstly, you need to determine how many possible field components will 
% be in the data file here, we assume this is only one snapshot in the file,
% this snapshot has 6 components. (for EM simulation, there is always 6 fields)
nComp = 6;  %%%% 


% open file
fid = fopen( fname, 'rb' ); % target file
if( fid == -1 )
    return;
end;

%%% read header
n0 = fread( fid, 1, '*int32' );
n1 = fread( fid, 1, '*int32' );
n2 = fread( fid, 1, '*int32' );
n3 = fread( fid, 1, '*int32' );
ver = fread( fid, 1, '*int32' );

%%% make sure it is the new version
if( ver ~= 1 ) return; end;

%%% face snapshot part
%%% the number of face snapshot in the data file
nFS = fread( fid, 1, '*int32' );

%%%% following code assume there is only one snapshot in the file.
%%%% if there are more, you need to use your data structure to store
%%%% information

if nFS > 0,
    %%% there is face snapshot
    snapFun = cell(nFS,1);
    
    for ik = 1 : nFS,    %%% read face snapshot one by one      
        nType = fread( fid, 1, '*int32' ); %%% face type (free face or solid face)
        n1D = fread( fid, 1, '*int32' );   %%% 1st dimension length
        nNameLen = fread( fid, 1, '*int32' );   %%% snapshot length
        sFsName = fread( fid, double(nNameLen), '*char' );   %%% snapshot name
        nPoint = fread( fid, 1, '*int32' );  %%% total point number, so the array will be (n1D) * (nPoint/n1D)
        n2D = nPoint / n1D;
        
        dat_tmp = cell(6,1);
        pos = zeros(nPoint,3);

        %%%% all point will include a strutured information
        for ig = 1 : nPoint
            %%% x, y, z position
            x = fread( fid, 1, '*double' );   %%% point x position
            y = fread( fid, 1, '*double' );   %%% point y position
            z = fread( fid, 1, '*double' );   %%% point z position
            
            pos(ig, :) = [x y z];
            Ndisplay = fread( fid, 1, '*int32' );  %%% trace length for this receiver  
            Ndisplay = Ndisplay / 4;      %%% this length is the size of 'char', need to convert to 'float'  
            
            if ig == 1
                bit_flag = 1;
                for iComp = 1 : nComp,   %%% for all possible components
                    flag = bitand( mask_for_case, bit_flag);
                    if flag ~= 0
                        dat_tmp{iComp} = zeros(nPoint,nComp,Ndisplay);
                    end;
                    bit_flag = bitshift( bit_flag, 1 );
                end;
            end
        
            bit_flag = 1;
            for iComp = 1 : nComp,   %%% for all possible components 
                flag = bitand( mask_for_case, bit_flag);
                if flag ~= 0            
                    v = fread( fid, double(Ndisplay), '*float' ); 
                    dat_tmp{iComp}(ig,1:Ndisplay) = v;
                    %fss(ig, iComp, :) = v;  
                end;
                bit_flag = bitshift( bit_flag, 1 );
            end;
        end; 

        
        bit_flag = 1;
        for iComp = 1 : nComp,   %%% for all possible components
            flag = bitand( mask_for_case, bit_flag);
            if flag ~= 0 
                switch iComp
                    case 1
                        for ih = 1:Ndisplay
                            snapFun{ik}.Ex(1:n1D,1:n2D,ih) ...
                                = reshape(dat_tmp{iComp}(:,ih),n1D, n2D);
                        end
                    case 2
                        for ih = 1:Ndisplay
                            snapFun{ik}.Ey(1:n1D,1:n2D,ih) ...
                                = reshape(dat_tmp{iComp}(:,ih),n1D, n2D);
                        end
                    case 3
                        for ih = 1:Ndisplay
                            snapFun{ik}.Ez(1:n1D,1:n2D,ih)  ...
                                = reshape(dat_tmp{iComp}(:,ih),n1D, n2D);
                        end
                    case 4
                        for ih = 1:Ndisplay
                            snapFun{ik}.Hx(1:n1D,1:n2D,ih)  ...
                                = reshape(dat_tmp{iComp}(:,ih),n1D, n2D);
                        end
                    case 5
                        for ih = 1:Ndisplay
                        snapFun{ik}.Hy(1:n1D,1:n2D,ih)  ...
                            = reshape(dat_tmp{iComp}(:,ih),n1D, n2D);
                        end
                    case 6
                        for ih = 1:Ndisplay
                        snapFun{ik}.Hz(1:n1D,1:n2D,ih)  ...
                            = reshape(dat_tmp{iComp}(:,ih),n1D, n2D);
                        end
                end
            end;
            bit_flag = bitshift( bit_flag, 1 );
        end;
            
        snapFun{ik}.type = nType;
        snapFun{ik}.name = sFsName;
        snapFun{ik}.dim1 = n1D;
        snapFun{ik}.dim2 = n2D;
        %snapshotFun{k}.dim3 = 
        snapFun{ik}.Ndisplay = Ndisplay;
        snapFun{ik}.x = reshape( pos(:, 1), n1D, n2D ); 
        snapFun{ik}.y = reshape( pos(:, 2), n1D, n2D );
        snapFun{ik}.z = reshape( pos(:, 3), n1D, n2D );
  
    end; 
    
end;

%%% volume snapshot part, here is 0, skip
nBS = fread( fid, 1, '*int32' );

%%%% for EL solver, we use face snapshot only, then we skip following data file
fclose( fid );


end




