%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%  purpose: this is a demo code to load & show the binary snpashot data file generated by
%%%%  the WCT GUI
%%%%
%%%%  copyright:   wave computation technology
%%%%  Author:      mengqing yuan
%%%%  contact:     mqyuan@wavenology.com
%%%%  date:        03/28/2016
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all;

%%%%%%
nComp = 6;  %%%% firstly, you need to determine how many possible field components will be in the data file
            %%%% here, we assume this is only one snapshot in the file, this snapshot has 6 components
%%%%%%
Ex = 1;     %%%%% bit mask for each component
Ey = 2;     
Ez = 4;
Hx = 8;
Hy = 16;
Hz = 32;

%%%%% in this case, we know we capture "Ex, Ey & Ez", so, here, we enable
%%%%% these mask
%mask_for_case = bitor( bitor(Ex, Ey), Ez );
mask_for_case =  Ez ;

% open file
fid = fopen( 'Station_grid_hit2_short_conn_snap.dat', 'rb' ); % target file
if( fid == -1 )
    return;
end;

%%% read header
n0 = fread( fid, 1, '*int32' );
n1 = fread( fid, 1, '*int32' );
n2 = fread( fid, 1, '*int32' );
n3 = fread( fid, 1, '*int32' );
ver = fread( fid, 1, '*int32' );

%%% make sure it is the new version
if( ver ~= 1 ) return; end;

%%% face snapshot part
%%% the number of face snapshot in the data file
nFS = fread( fid, 1, '*int32' );

%%%% following code assume there is only one snapshot in the file.
%%%% if there are more, you need to use your data structure to store
%%%% information

if nFS > 0,
    %%% there is face snapshot
    
    for k = 1 : 2,    %%% read face snapshot one by one    
        nType = fread( fid, 1, '*int32' ); %%% face type (free face or solid face)
        n1D = fread( fid, 1, '*int32' );   %%% 1st dimension length
        nNameLen = fread( fid, 1, '*int32' );   %%% snapshot length
        sFsName = fread( fid, double(nNameLen), '*char' );   %%% snapshot name
        nPoint = fread( fid, 1, '*int32' );  %%% total point number, so the array will be (n1D) * (nPoint/n1D)
        
        %%%% all point will include a strutured information
        for j = 1 : nPoint
            %%% x, y, z position
            x = fread( fid, 1, '*double' );   %%% point x position
            y = fread( fid, 1, '*double' );   %%% point y position
            z = fread( fid, 1, '*double' );   %%% point z position
            
            pos(j, :) = [x y z];
            len = fread( fid, 1, '*int32' );  %%% trace length for this receiver  
            len = len / 4;      %%% this length is the size of 'char', need to convert to 'float'  
            
            bit_flag = 1;
            for iComp = 1 : nComp,   %%% for all possible components 
                flag = bitand(mask_for_case, bit_flag);
                if( flag ~= 0 );           
                    v = fread( fid, double(len), '*float' ); 
                    fss(j, iComp, :) = v;  
                end;
                bit_flag = bitshift( bit_flag, 1 );
            end;
        end;        
    end; 
    
end;

%%% volume snapshot part, here is 0, skip
nBS = fread( fid, 1, '*int32' );

%%%% for EL solver, we use face snapshot only, then we skip following data file
fclose( fid );

%%%% display,  for this case, it is 2D planar plane, so, the data is an 2D array
%%% for this 2D array, the inner point number is 'n1D'
n2D = nPoint / n1D;

xPos = pos(:, 1);    xPos = reshape( xPos, n1D, n2D );
yPos = pos(:, 2);    yPos = reshape( yPos, n1D, n2D );
zPos = pos(:, 3);    zPos = reshape( zPos, n1D, n2D );

fss = double( fss );    % convert to double for displaying purpose

Ex = squeeze( fss(:,1,: ) );
Ey = squeeze( fss(:,2,: ) );
Ez = squeeze( fss(:,3,: ) );

%%%%%% here, we will show the Ex snapshot in a 2D plane
sz = size( Ez );
time_trace_len = sz(2);   %%% get transient trace length

time_id = floor( time_trace_len / 2 ); %%% we will display the middle frame

Ez_t = squeeze( Ez(:, time_id) );      %%% extract this frame
Ez_t = reshape( Ez_t, n1D, n2D );       %%% convert to 2D

figure;
mesh( xPos,yPos,Ez_t );
contour( xPos,yPos,Ez_t );

%axis equal

shading flat;
colorbar;





