function net = nn_simpe(x,t,hiddenNeuronNum)
% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 02-Mar-2017 14:46:16
%
% This script assumes these variables are defined:
%
%   x - input data.
%   t - target data.


%% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.  scaled conjugate gradient method
% Backpropagation training functions that use Jacobian derivatives
%  
%     These algorithms can be faster but require more memory than gradient
%     backpropation.  They are also not supported on GPU hardware.
%  
%     trainlm   - Levenberg-Marquardt backpropagation.
%     trainbr   - Bayesian Regulation backpropagation.
%  
%   Backpropagation training functions that use gradient derivatives
%  
%     These algorithms may not be as fast as Jacobian backpropagation.
%     They are supported on GPU hardware with the Parallel Computing Toolbox.
%  
%     trainbfg  - BFGS quasi-Newton backpropagation.
%     traincgb  - Conjugate gradient backpropagation with Powell-Beale restarts.
%     traincgf  - Conjugate gradient backpropagation with Fletcher-Reeves updates.
%     traincgp  - Conjugate gradient backpropagation with Polak-Ribiere updates.
%     traingd   - Gradient descent backpropagation.
%     traingda  - Gradient descent with adaptive lr backpropagation.
%     traingdm  - Gradient descent with momentum.
%     traingdx  - Gradient descent w/momentum & adaptive lr backpropagation.
%     trainoss  - One step secant backpropagation.
%     trainrp   - RPROP backpropagation.
%     trainscg  - Scaled conjugate gradient backpropagation.
%  
%   Supervised weight/bias training functions
%  
%     trainb    - Batch training with weight & bias learning rules.
%     trainc    - Cyclical order weight/bias training.
%     trainr    - Random order weight/bias training.
%     trains    - Sequential order weight/bias training.
%  
%   Unsupervised weight/bias training functions
%  
%     trainbu   - Unsupervised batch training with weight & bias learning rules.
%     trainru   - Unsupervised random order weight/bias training.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

%% Create a Fitting Network
net = fitnet(hiddenNeuronNum,trainFcn);

%% Choose Input and Output Pre/Post-Processing Functions
% For a list of all processing functions type: help nnprocess
%     fixunknowns        - Processes matrix rows with unknown values.
%     mapminmax          - Map matrix row minimum and maximum values to [-1 1].
%     mapstd             - Map matrix row means and deviations to standard values.
%     processpca         - Processes rows of matrix with principal component analysis.
%     removeconstantrows - Remove matrix rows with constant values.
%     removerows         - Remove matrix rows with specified indices.
net.input.processFcns = {'removeconstantrows','mapminmax'};
net.output.processFcns = {'removeconstantrows','mapminmax'};


% Setup Division of Data for Training, Validation, Testing
% For a list of all data division functions type: help nndivide
net.divideFcn = 'dividerand';  % Divide data randomly
net.divideMode = 'sample';  % Divide up every sample
net.divideParam.trainRatio = 100/100;
net.divideParam.valRatio = 0/100;
net.divideParam.testRatio = 0/100;

% Choose a Performance Function
% For a list of all performance functions type: help nnperformance
%   mae          - Mean absolute error performance function.
%   mse          - Mean squared error performance function.
%   sae          - Sum absolute error performance function.
%   sse          - Sum squared error performance function.
%   crossentropy - Cross-entropy performance.
%   msesparse    - Mean squared error performance function with L2 weight and sparsity regularizers.
net.performFcn = 'mse';  % Mean Squared Error

net.trainParam.showWindow = false;  % donot show the train window

% Train the Network
% [net,tr] = train(net,x,t);
[net] = train(net,x,t);
% Test the Network
% y = net(x);
% e = gsubtract(t,y);
% performance = perform(net,t,y)

% Recalculate Training, Validation and Test Performance
% trainTargets = t .* tr.trainMask{1};
% valTargets = t .* tr.valMask{1};
% testTargets = t .* tr.testMask{1};
% trainPerformance = perform(net,trainTargets,y)
% valPerformance = perform(net,valTargets,y)
% testPerformance = perform(net,testTargets,y)


end
