% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 02-Mar-2017 14:46:16
%
% This script assumes these variables are defined:
%
%   nn_input - input data.
%   nn_output - target data.

x = nn_input;
t = nn_output;

%% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.  scaled conjugate gradient method
% Backpropagation training functions that use Jacobian derivatives
%  
%     These algorithms can be faster but require more memory than gradient
%     backpropation.  They are also not supported on GPU hardware.
%  
%     trainlm   - Levenberg-Marquardt backpropagation.
%     trainbr   - Bayesian Regulation backpropagation.
%  
%   Backpropagation training functions that use gradient derivatives
%  
%     These algorithms may not be as fast as Jacobian backpropagation.
%     They are supported on GPU hardware with the Parallel Computing Toolbox.
%  
%     trainbfg  - BFGS quasi-Newton backpropagation.
%     traincgb  - Conjugate gradient backpropagation with Powell-Beale restarts.
%     traincgf  - Conjugate gradient backpropagation with Fletcher-Reeves updates.
%     traincgp  - Conjugate gradient backpropagation with Polak-Ribiere updates.
%     traingd   - Gradient descent backpropagation.
%     traingda  - Gradient descent with adaptive lr backpropagation.
%     traingdm  - Gradient descent with momentum.
%     traingdx  - Gradient descent w/momentum & adaptive lr backpropagation.
%     trainoss  - One step secant backpropagation.
%     trainrp   - RPROP backpropagation.
%     trainscg  - Scaled conjugate gradient backpropagation.
%  
%   Supervised weight/bias training functions
%  
%     trainb    - Batch training with weight & bias learning rules.
%     trainc    - Cyclical order weight/bias training.
%     trainr    - Random order weight/bias training.
%     trains    - Sequential order weight/bias training.
%  
%   Unsupervised weight/bias training functions
%  
%     trainbu   - Unsupervised batch training with weight & bias learning rules.
%     trainru   - Unsupervised random order weight/bias training.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

%% Create a Fitting Network
hiddenLayerSize = 4;
net = fitnet(hiddenLayerSize,trainFcn);

%% Choose Input and Output Pre/Post-Processing Functions
% For a list of all processing functions type: help nnprocess
%     fixunknowns        - Processes matrix rows with unknown values.
%     mapminmax          - Map matrix row minimum and maximum values to [-1 1].
%     mapstd             - Map matrix row means and deviations to standard values.
%     processpca         - Processes rows of matrix with principal component analysis.
%     removeconstantrows - Remove matrix rows with constant values.
%     removerows         - Remove matrix rows with specified indices.
net.input.processFcns = {'removeconstantrows','mapminmax'};
net.output.processFcns = {'removeconstantrows','mapminmax'};


% Setup Division of Data for Training, Validation, Testing
% For a list of all data division functions type: help nndivide
net.divideFcn = 'dividerand';  % Divide data randomly
net.divideMode = 'sample';  % Divide up every sample
net.divideParam.trainRatio = 60/100;
net.divideParam.valRatio = 20/100;
net.divideParam.testRatio = 20/100;

% Choose a Performance Function
% For a list of all performance functions type: help nnperformance
%   mae          - Mean absolute error performance function.
%   mse          - Mean squared error performance function.
%   sae          - Sum absolute error performance function.
%   sse          - Sum squared error performance function.
%   crossentropy - Cross-entropy performance.
%   msesparse    - Mean squared error performance function with L2 weight and sparsity regularizers.
net.performFcn = 'mse';  % Mean Squared Error

% Choose Plot Functions
% For a list of all plot functions type: help nnplot
%    plotconfusion  - Plot classification confusion matrix.
%    ploterrcorr    - Plot autocorrelation of error time series.
%    ploterrhist    - Plot error histogram.
%    plotfit        - Plot function fit.
%    plotinerrcorr  - Plot input to error time series cross-correlation.
%    plotperform    - Plot network performance.
%    plotregression - Plot linear regression.
%    plotresponse   - Plot dynamic network time-series response.
%    plotroc        - Plot receiver operating characteristic.
%    plotsomhits    - Plot self-organizing map sample hits.
%    plotsomnc      - Plot Self-organizing map neighbor connections.
%    plotsomnd      - Plot Self-organizing map neighbor distances.
%    plotsomplanes  - Plot self-organizing map weight planes.
%    plotsompos     - Plot self-organizing map weight positions.
%    plotsomtop     - Plot self-organizing map topology.
%    plottrainstate - Plot training state values.
%    plotwb         - Plot Hinton diagrams of weight and bias values.
net.plotFcns = {'plotperform','plottrainstate','ploterrhist', ...
    'plotregression', 'plotfit'};

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y)

% Recalculate Training, Validation and Test Performance
trainTargets = t .* tr.trainMask{1};
valTargets = t .* tr.valMask{1};
testTargets = t .* tr.testMask{1};
trainPerformance = perform(net,trainTargets,y)
valPerformance = perform(net,valTargets,y)
testPerformance = perform(net,testTargets,y)

% View the Network
%view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)

% Deployment
% Change the (false) values to (true) to enable the following code blocks.
% See the help for each generation function for more information.
if (false)
    % Generate MATLAB function for neural network for application
    % deployment in MATLAB scripts or with MATLAB Compiler and Builder
    % tools, or simply to examine the calculations your trained neural
    % network performs.
    genFunction(net,'myNeuralNetworkFunction');
    y = myNeuralNetworkFunction(x);
end
if (false)
    % Generate a matrix-only MATLAB function for neural network code
    % generation with MATLAB Coder tools.
    genFunction(net,'myNeuralNetworkFunction','MatrixOnly','yes');
    y = myNeuralNetworkFunction(x);
end
if (false)
    % Generate a Simulink diagram for simulation or deployment with.
    % Simulink Coder tools.
    gensim(net);
end
