function save_data_to_matlab2(Rmtx, Lmtx, Cmtx, ...
    pt_start, pt_end, dv, re, shape, dim1, dim2, len, ...
    R_pul, Lin_pul, sig, mur, ...
    bran_type,bran_name, nod_start, nod_end, bran_out, nod_out, ...
    Nbran_out, Nnod_out, Nfit, frq, fpath, fname,nod_name,Rsoil, ...
     grp_id, grp_type, pt_2d) 
 
 sname = [fpath, fname];
save(sname,  'Rmtx', 'Lmtx', 'Cmtx', 'pt_start', 'pt_end', 'dv', 're', 'shape', 'dim1', 'dim2', 'len', ...
    'R_pul', 'Lin_pul', 'sig', 'mur', ...
    'bran_type','bran_name', 'nod_start', 'nod_end',  ...
    'bran_out', 'nod_out', 'Nbran_out', 'Nnod_out', 'Nfit', 'frq', ...
    'fpath','fname','nod_name','Rsoil', ...
     'grp_id','grp_type', 'pt_2d');
% save(sname, pt_start, pt_end, dv, re, len, Ndat_3D, ...
%     bran_type, bran_name, nod_start, nod_end, ...
%     bran_output, nod_output, Nbran_out, Nnod_out);

end
