function save_grid_data_to_matlab(Rgrid, Lgrid, Cgrid,Rself_grid, Lself_grid, ...
    Rfit_grid, Lfit_grid, Rdc_fit_grid, Ldc_fit_grid, ...
    pt_start_grid, pt_end_grid, dv_grid, re_grid, ...
    shape_grid, dim1_grid, dim2_grid, len_grid, ...
    R_pul_grid, Lin_pul_grid, sig_grid, mur_grid, ...
    bran_name_grid, nod_start_grid, nod_end_grid, nod_name_grid,  ...
    bran_out_grid, nod_out_grid, ...
    Nbran_out_grid, Nnod_out_grid, Nnod_gnd_grid,nod_gnd_grid, Nfit_grid, frq_grid, ...
    fpath_grid, fname_grid,Rgrod)

sname = [fpath_grid, fname_grid,'_grid'];

save(sname,  'Rgrid', 'Lgrid', 'Cgrid','Rself_grid', 'Lself_grid', ...
    'Rfit_grid', 'Lfit_grid', 'Rdc_fit_grid', 'Ldc_fit_grid', ...
    'pt_start_grid', 'pt_end_grid', 'dv_grid', 're_grid', ...
    'shape_grid', 'dim1_grid', 'dim2_grid', 'len_grid', ...
    'R_pul_grid', 'Lin_pul_grid', 'sig_grid', 'mur_grid', ...
    'bran_name_grid', 'nod_start_grid', 'nod_end_grid', 'nod_name_grid', ...
    'bran_out_grid', 'nod_out_grid', ...
    'Nbran_out_grid', 'Nnod_out_grid', 'Nnod_gnd_grid', 'nod_gnd_grid','Nfit_grid', 'frq_grid', ...
    'fpath_grid','fname_grid','Rgrod');

end
