function spice_subckt_self_vf_0(Rmtx,Lmtx,Cmtx, Rfit,Lfit, bran_name,nod_name, ...
    nod_start, nod_end,bran_out, nod_out, fpath, fname,re,len)
%  Function:       spice_subckt_self_vf
%  Description:    Generate the spice netlist for built PEEC network.
%                  Vector fitting is added as in "Systematic development of
%                  transmission-line models for interconnects with
%                  frequency-dependent losses"
%                  1. header and output node
%                  2. network
%                        -  (1). self R + full L (R + 0Vdc + L)
%                              - (1).a  measurment branch  (R + 0Vdc + L )
%                              - (1).b  no measurment ( R + L )
%                        -  (2). self R + mutual R + full L
%                              (R + 0Vdc + E1+E2+...+ L)
%                              - (2).a  measurment branch (R + 0Vdc + E1+E2+...+ L)
%                              - (2).b  no measurment (R + E1+E2+...+ L)
%                  3. end of netlist
%  Calls:
%
%  Input:          Rmtx  --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lmtx  --  L matrix calculated using PEEC (N*N)(H)
%                  bran_name  --  branch name of all conductors
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  bran_type  --  branch type of all conductors(measurmnt or not)
%                  nod_out    --  output node
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2014-12-24
%  Updated:        2016.04.09  Remove unnecessery unknowns.
%  Updated:        2016.08.06  Add complex pole branch.
nod_out=unique(nod_out(:,:),'rows');

Pmtx=inv(Cmtx);
[common_delete,flag,re_2,len_2] = commonnode(re,len,nod_name,Pmtx);

[Nr,Pr]=NODE_PMERGE(nod_name,flag,common_delete,re_2,len_2,Pmtx);

nod_name=Nr;
Pmtx=Pr;
Cmtx=inv(Pmtx);


err_ML = 1e-3;
err_MR = 1e-6;
err_MC = 1e-9;

% fprinf doesnot support sparse matrix, thus change sparse matrix
Rmtx = full(Rmtx);
Lmtx = full(Lmtx);
Cmtx = full(Cmtx);
Rfit = full(Rfit);
Lfit = full(Lfit);


Nbran     = size(Lmtx,1);
Nnod      = size(Cmtx,1);
Nbran_out = size(bran_out,1);
Nnod_out  = size(nod_out,1);

Nbran1=Nbran;
Nbran2=0;



%% 1. Write the head of netlist (external port)
fid = fopen([fpath, fname,'.cir'],'w+');

fprintf(fid,'.SUBCKT %s ', fname);
% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
for ik = 1:Nnod_out
    fprintf(fid,'%s ',deblank(nod_out(ik,:)));
    if mod(ik,5)==0 && ik~=Nnod_out
        fprintf(fid,'\n+ ');
    end
end

if Nnod_out>0 && Nbran_out>0
    fprintf(fid,'\n+ ');
end

for ik = 1:Nbran_out
    fprintf(fid,'%s ', deblank(bran_out(ik,:)));
    if mod(ik,5)==0 && ik~=Nbran_out
        fprintf(fid,'\n+ ');
    end
end
fprintf(fid,'\n');

%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');


%% 3. Write R+L Network
NR = 0;
NL = 0;
NC = 0;
NK = 0;
NE = 0; % no. of added point for E (used for mutual R)
NM = 0; % no. of current measurment branch
NV = 0; % no. of vector fitting node
vfcplx_flag = 0;% flag of vector fitting complex node

Ls = zeros(Nbran,1);
Ls(1:Nbran) = diag(Lmtx);

% define the direction of the first condutor as reference direction
% cofLSign = sign(Lmtx(1:Nbran,1));

cofK = zeros(Nbran,1);
cofMR = zeros(Nbran,1);

if Nbran > 1
    for ik = 1:Nbran
        if ik<=Nbran1
        
        idRsM = abs(Rmtx(ik+1:end,ik)) > 0;
        flgRm = sum(idRsM);
        
        Nfit = find(Rfit(ik,:), 1, 'last');
        
        
        fprintf(fid,'* *  Branch  %s - %s \n', deblank(nod_start(ik,:)), deblank(nod_end(ik,:)));
        
        %% (1). self R + full L (R + 0Vdc + L)
        if  flgRm==0
            
            %% R - (1)-a, (1)-b use the same R writing part
            Rtmp = max(Rmtx(ik,ik), 1e-6);
            %nodR = ['nR_', num2str(ik)];
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
                NR, deblank(nod_start(ik,:)), ik, Rtmp*1e3);
            
            %% 2-a. with current measurment
            if ~isempty(bran_out) && ismember(bran_name(ik,:),bran_out,'rows')
                
                % add current measurment block
                NM = NM+1;
                %nodM = ['nM_' num2str(ik)];
                fprintf(fid,'*  Mearsure Branch Current %s \n', deblank(bran_name(ik,:)));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, deblank(bran_name(ik,:)), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, deblank(bran_name(ik,:)));
                %nodL1 = nodM;
                
                if Nfit>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit+1;
                    
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            
                            if isreal(Rfit(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*Lfit(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit(ik,ih);
                                R2 = Rfit(ik,ih+1);
                                L1 = Lfit(ik,ih);
                                L2 = Lfit(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*LC);
                            end
                            
                        elseif ih>1 && Nfit>0 && ih~=vfcplx_flag
                            NV = NV+1;
                            
                            if isreal(Rfit(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit(ik,ih);
                                R2 = Rfit(ik,ih+1);
                                L1 = Lfit(ik,ih);
                                L2 = Lfit(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                        NL, ik, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                end
                
                
                %% 2-b. no current measurment
            else
                if Nfit>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit+1;
                    
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            
                            if isreal(Rfit(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*Lfit(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit(ik,ih);
                                R2 = Rfit(ik,ih+1);
                                L1 = Lfit(ik,ih);
                                L2 = Lfit(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*LC);
                                
                            end
                            
                        elseif ih>1 && Nfit>0 && ih~=vfcplx_flag
                            NV = NV+1;
                            
                            if isreal(Rfit(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit(ik,ih);
                                R2 = Rfit(ik,ih+1);
                                L1 = Lfit(ik,ih);
                                L2 = Lfit(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                    end
                    
                    %nodL1 = nodR;
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                else
                    
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                        NL, ik, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                end
                
            end
            
            %% K -- 2-a, 2-b use the same K writing part
            cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    

                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
%                     fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
%                         NK, ik, ih, 0.3);

                end
            end
            

            
            
            
            
            %% (2). self R + mutual R + full L (R + 0Vdc + E1+E2+...+ L)
        elseif flgRm>0
            
            %% R -- 3-a, 3-b use the same R writing part
            %nodR = ['nR_', num2str(ik)];
            Rtmp = max(Rmtx(ik,ik), 1e-6);
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
                NR, deblank(nod_start(ik,:)), ik, Rtmp*1e3);
            
            %% 3-a. with current measurment (R + 0Vdc + E1+E2+...+ L)
            if ~isempty(bran_out) && ismember(bran_name(ik,:),bran_out,'rows')
                
                % add current measurment block
                %nodM = ['nM_', num2str(ik)];
                NM = NM+1;
                fprintf(fid,'*  Mearsure Branch Current %s \n',deblank(bran_name(ik,:)));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, deblank(bran_name(ik,:)), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, deblank(bran_name(ik,:)));
                
                %nodE0 = nodM;   % first node of E series (mutual R)
                %nodE2 = nodE0;  % initial nodE2 for case of no E exist
                
                % E - mutual R (VCVS)
                cofMR(1:Nbran) = Rmtx(1:Nbran,ik)./Rmtx(ik,ik);
                cofMR(ik) = 0;
                idRsM = find(abs(cofMR) > err_MR);
                NMR = length(idRsM);
                
                for ih = 1:NMR
                    %nodRex = ['nR_', num2str(ind(ih))];
                    if ih==1 %&& ih~=ik % first node is set to be nodE0
                        NE = NE+1;
                        %nodE1 = ['nE_', num2str(NE)];
                        %nodE2 = nodE1;
                        fprintf(fid,'E_E%d  nM_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE, ik, NE, deblank(nod_start(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    elseif ih>1 %&& ih~=ik
                        NE = NE+1;
                        %nodE1 = ['nE_', num2str(NE-1)];
                        %nodE2 = ['nE_', num2str(NE)];
                        fprintf(fid,'E_E%d  nE_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE,  NE-1, NE, deblank(nod_start(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    end
                end
                
                if Nfit>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit+1;
                    
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            if NMR == 0
                                
                                if isreal(Rfit(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*Rfit(ik,ih));
                                    fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                        NV, ik, NV, 1e6*Lfit(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit(ik,ih);
                                    R2 = Rfit(ik,ih+1);
                                    L1 = Lfit(ik,ih);
                                    L2 = Lfit(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                        NV, ik, NV, 1e6*LC);
                                end
                                
                            elseif NMR >= 1
                                
                                if isreal(Rfit(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*Rfit(ik,ih));
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %fuH \n', ...
                                        NV, NE, NV, 1e6*Lfit(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit(ik,ih);
                                    R2 = Rfit(ik,ih+1);
                                    L1 = Lfit(ik,ih);
                                    L2 = Lfit(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nE_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %fuH \n', ...
                                        NV, NE, NV, 1e6*LC);
                                end
                            end
                        elseif ih>1 && Nfit>0 && ih~=vfcplx_flag
                            NV = NV+1;
                            
                            if isreal(Rfit(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit(ik,ih);
                                R2 = Rfit(ik,ih+1);
                                L1 = Lfit(ik,ih);
                                L2 = Lfit(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    if NMR == 0
                        fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                            NL, ik, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                    elseif NMR >= 1
                        fprintf(fid,'L_L%d  nE_%d  %s  %fuH \n', ...
                            NL, NE, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                    end
                end
                %% 3-b. no current measurment (R + E1+E2+...+ L)
            else
                %nodE0 = nodR;   % first node of E series (mutual R)
                %nodE2 = nodE0;  % initial nodE2 for case of no E exist
                
                % E - mutual R (VCVS)
                cofMR(1:Nbran) = Rmtx(1:Nbran,ik)./Rmtx(ik,ik);
                cofMR(ik) = 0;
                idRsM = find(abs(cofMR) > err_MR);
                NMR = length(idRsM);
                
                for ih = 1:NMR
                    if ih==1 %&& ih~=ik % first node is set to be nodE0
                        NE = NE+1;
                        fprintf(fid,'E_E%d  nR_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE, ik, NE, deblank(nod_start(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    elseif ih>1 %&& ih~=ik
                        NE = NE+1;
                        fprintf(fid,'E_E%d  nE_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE, NE-1, NE, deblank(nod_start(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    end
                end
                
                if Nfit>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit+1;
                    
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            
                            if NMR == 0
                                if isreal(Rfit(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*Rfit(ik,ih));
                                    fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                        NV, ik, NV, 1e6*Lfit(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit(ik,ih);
                                    R2 = Rfit(ik,ih+1);
                                    L1 = Lfit(ik,ih);
                                    L2 = Lfit(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                        NV, ik, NV, 1e6*LC);
                                end
                                
                            elseif NMR >= 1
                                if isreal(Rfit(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*Rfit(ik,ih));
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %fuH \n', ...
                                        NV, NE, NV, 1e6*Lfit(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit(ik,ih);
                                    R2 = Rfit(ik,ih+1);
                                    L1 = Lfit(ik,ih);
                                    L2 = Lfit(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nE_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %fm  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %fuH \n', ...
                                        NV, NE, NV, 1e6*LC);
                                end
                            end
                        elseif ih>1 && Nfit>0 && ih~=vfcplx_flag
                            NV = NV+1;
                            
                            if isreal(Rfit(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit(ik,ih);
                                R2 = Rfit(ik,ih+1);
                                L1 = Lfit(ik,ih);
                                L2 = Lfit(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    if NMR == 0
                        fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                            NL, ik, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                    elseif NMR >= 1
                        fprintf(fid,'L_L%d  nE_%d  %s  %fuH \n', ...
                            NL, NE, deblank(nod_end(ik,:)), 1e6*Ls(ik));
                    end
                end
            end
            
            %% K -- 3-a, 3-b use the same K writing part
            cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
%                     fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
%                         NK, ik, ih, 0.002);
                end
            end
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ground_grid
        else
        nod_mid = ['NMID',num2str(ik,'%.10d')];
        fprintf(fid,'* *  Ground Grid (%s - %s - %s)\n', ...
            nod_start(ik,:),nod_mid, nod_end(ik,:));
        
        %% (1). self R + full L (R + 0Vdc + L)
        % R
        Rtmp = max(Rmtx(ik,ik), 1e-6);
        %nodR = ['nR_', num2string(ik)];
        NR = NR+1;
        fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0\n', ...
            NR, nod_start(ik,:), ik, Rtmp*1e3/2);
        
        %% 2-a. with current measurment
        if ~isempty(bran_out) && ...
                ismember(bran_name(ik,:),bran_out,'rows')
            
            % add current measurment block
            NM = NM+1;
            %nodM = ['nM_' num2str(ik)];
            fprintf(fid,'*  Mearsure Branch Current %s \n', bran_name(ik,:));
            % 0V Vdc
            fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
            % H (CCVS for measuring current)
            fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name(ik,:), NM);
            fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name(ik,:));
            %nodL1 = nodM;
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                NL, ik, nod_mid, 1e6*Ls(ik)/2);
            
            %% 2-b. no current measurment
        else
            %nodL1 = nodR;
            NL = NL+1;
            fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                NL, ik, nod_mid, 1e6*Ls(ik)/2);
        end
        
        %% K -- 2-a, 2-b use the same K writing part
        cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
        for ih = ik+1:Nbran
            if cofK(ih) >= 1
                cofK(ih) = 0.9999;
            elseif cofK(ih) <= -1
                cofK(ih) = -0.9999;
            end
            
            if abs(cofK(ih)) > err_ML
                NK = NK+1;
                fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', NK, ik, ih, cofK(ih));
            end
        end
        
        % % % % % %
        fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0\n', ...
            NR+Nbran, nod_mid, ik+Nbran, Rtmp*1e3/2);
        fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
            NL+Nbran, ik+Nbran, nod_end(ik,:), 1e6*Ls(ik)/2);
        
        for ih = ik+1:Nbran
            if abs(cofK(ih)) > err_ML
                NK = NK+1;
                fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                    NK, ik+Nbran, ih+Nbran, cofK(ih));
            end
        end
        
        end
    end

    
elseif Nbran==1
    %% R - 2-a, 2-b use the same R writing part
        fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', 1, deblank(nod_start(1,:)), 1, Rmtx(1,1)*1e3);
    
    %% 2-a. with current measurment
    if ~isempty(bran_out) && ismember(bran_name(1,:),bran_out,'rows')
        
        Nfit = find(Rfit(1,:), 1, 'last');
        
        % add current measurment block
        %nodM = ['nM_' num2str(ik)];
        fprintf(fid,'*  Mearsure Branch Current %s \n',deblank(bran_name(1,:)));
        % 0V Vdc
        fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', 1, 1, 1);
        % H (CCVS for measuring current)
        fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', 1, deblank(bran_name(1,:)), 1);
        fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', 1, deblank(bran_name(1,:)));
        %nodL1 = nodM;
        
        if Nfit>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit+1;
            
            for ih = 1:Nfit
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rfit(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rfit(ik,ih));
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*Lfit(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit(ik,ih);
                        R2 = Rfit(ik,ih+1);
                        L1 = Lfit(ik,ih);
                        L2 = Lfit(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                elseif ih>1 && Nfit>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rfit(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rfit(ik,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*Lfit(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit(ik,ih);
                        R2 = Rfit(ik,ih+1);
                        L1 = Lfit(ik,ih);
                        L2 = Lfit(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, NV, deblank(nod_end(1,:)), 1e6*Ls(1));
        else
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', NL, 1, deblank(nod_end(1,:)), 1e6*Ls(1));
            
        end
        %% 2-b. no current measurment
    else
        Nfit = find(Rfit(1,:), 1, 'last');
        %nodL1 = nodR;
        if Nfit>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit+1;
            
            for ih = 1:Nfit
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rfit(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rfit(1,ih));
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*Lfit(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit(ik,ih);
                        R2 = Rfit(ik,ih+1);
                        L1 = Lfit(ik,ih);
                        L2 = Lfit(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                elseif ih>1 && Nfit>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rfit(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rfit(1,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*Lfit(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit(ik,ih);
                        R2 = Rfit(ik,ih+1);
                        L1 = Lfit(ik,ih);
                        L2 = Lfit(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, NV, deblank(nod_end(1,:)), 1e6*Ls(1));
        else
            
            fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', NL, 1, deblank(nod_end(1,:)), 1e6*Ls(1));
        end
    end
    
end


%% 4. Write C Network
if ~isempty(Cmtx)
    for ik = 1:Nnod
        fprintf(fid,'* *  Node  %s to other nodes\n', deblank(nod_name(ik,:)));
        Cstmp = sum(Cmtx(ik,:));
%         Cstmp=0;
% Cstmp=100e-12;
        if (Cstmp)>1e-6
            NC = NC+1;
            fprintf(fid,'C_C%d  %s  0  %euF \n', NC, deblank(nod_name(ik,:)), Cstmp*1e6);
        elseif (Cstmp)>1e-14
            NC = NC+1;
            fprintf(fid,'C_C%d  %s  0  %epF \n', NC, deblank(nod_name(ik,:)), Cstmp*1e12);
        end
        
        % mutual capacitance

        for ig = ik+1:Nnod
            
            Cmtmp = -Cmtx(ik,ig);
%             Cmtmp = 0;
%             Cmtmp=5e-12;
% Cmtmp=0;

            if (Cmtmp)>1e-6
                if  (nod_name(ik,:))==(nod_name(ig,:))
                else
                NC = NC+1;                
                fprintf(fid,'C_C%d  %s  %s  %euF \n', ...
                    NC, deblank(nod_name(ik,:)),deblank(nod_name(ig,:)),Cmtmp*1e6);
                end
            elseif (Cmtmp)>1e-14
                if  (nod_name(ik,:))==(nod_name(ig,:))
                else
                NC = NC+1;

                fprintf(fid,'C_C%d  %s  %s  %epF \n', ...
                    NC, deblank(nod_name(ik,:)),deblank(nod_name(ig,:)),Cmtmp*1e12);
                end
            end
        end
    end
end
    

%% Adding file End
fprintf(fid,'.ENDS %s \n', fname);
%% 3.b Write the GND node
% Adding nonlinear ground resistance modeling soil ionization effect

% E0 = 350e3;  % 400kV
% RGname =[fname,'_Rion',];
% NRG = 0;
% for ik = 1:Nbran2
%     Ig = 1/(2*pi)*E0*Rsoil/(Rgrod(ik)^2);
%     
%     nod_mid = ['NMID',num2str(Nbran1+ik,'%.10d')];
%     fprintf(fid,'*  Ground rod %d - %s \n', ik, nod_mid);
%     
%     NRG = NRG+1;
%     fprintf(fid,'X%d  %s  %s PARAMS: Ig=%.2f \n', ...
%         NRG, nod_mid, RGname, Ig);
% end
% 
% fprintf(fid,'.ENDS %s \n', fname);

%% 4. Adding nonlinear ground resistance

% fprintf(fid,'* Nonlinear Ground Resistance Used in Ground Grid\n');
% fprintf(fid,'.SUBCKT  %s  1  PARAMS: Ig=1000  R0=20 \n', RGname);
% fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
% fprintf(fid,'V_I_SENSE  2  3  0V \n');
% fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
% fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
% fprintf(fid,'E_VAR  3  0 \n');
% fprintf(fid,'+  VALUE={V(4)*{R0}/SQRT(1+ABS(V(4))/{Ig})} \n');
% fprintf(fid,'.ENDS %s \n', RGname);
fclose(fid);


end


