/******************************************************************************
 * Touchstone Format Export Implementation
 * 
 * Comprehensive Touchstone file format support for S-parameter export
 ******************************************************************************/

#include "touchstone_export.h"
#include <string.h>
#include <math.h>
#include <stdlib.h>

#if !defined(_MSC_VER)
#include <complex.h>
#define SPARAM_REAL(z) creal(z)
#define SPARAM_IMAG(z) cimag(z)
#define SPARAM_ABS(z) cabs(z)
#define SPARAM_ARG(z) carg(z)
#else
// MSVC compatibility
#define SPARAM_REAL(z) ((z).re)
#define SPARAM_IMAG(z) ((z).im)
#define SPARAM_ABS(z) (sqrt((z).re*(z).re + (z).im*(z).im))
#define SPARAM_ARG(z) (atan2((z).im, (z).re))
#endif

/******************************************************************************
 * Helper Functions
 ******************************************************************************/

static double convert_frequency(double freq_hz, touchstone_freq_unit_t unit) {
    switch (unit) {
        case TOUCHSTONE_FREQ_HZ:  return freq_hz;
        case TOUCHSTONE_FREQ_KHZ: return freq_hz / 1e3;
        case TOUCHSTONE_FREQ_MHZ: return freq_hz / 1e6;
        case TOUCHSTONE_FREQ_GHZ: return freq_hz / 1e9;
        default: return freq_hz;
    }
}

static const char* get_freq_unit_string(touchstone_freq_unit_t unit) {
    switch (unit) {
        case TOUCHSTONE_FREQ_HZ:  return "Hz";
        case TOUCHSTONE_FREQ_KHZ: return "kHz";
        case TOUCHSTONE_FREQ_MHZ: return "MHz";
        case TOUCHSTONE_FREQ_GHZ: return "GHz";
        default: return "Hz";
    }
}

static const char* get_format_string(touchstone_format_t format) {
    switch (format) {
        case TOUCHSTONE_FORMAT_MA: return "MA";
        case TOUCHSTONE_FORMAT_DB: return "DB";
        case TOUCHSTONE_FORMAT_RI: return "RI";
        default: return "RI";
    }
}

/******************************************************************************
 * Public Functions
 ******************************************************************************/

touchstone_export_options_t touchstone_get_default_options(void) {
    touchstone_export_options_t opts = {0};
    opts.data_format = TOUCHSTONE_FORMAT_RI;
    opts.freq_unit = TOUCHSTONE_FREQ_GHZ;
    opts.reference_impedance = 50.0;
    opts.port_impedances = NULL;
    opts.include_comments = true;
    opts.include_port_names = true;
    opts.description = NULL;
    opts.precision = 6;
    return opts;
}

int touchstone_generate_filename(
    const char* base_filename,
    int num_ports,
    char* output_buffer,
    size_t buffer_size
) {
    if (!base_filename || !output_buffer || num_ports < 1) {
        return -1;
    }
    
    // Generate .sNp filename
    int written = snprintf(output_buffer, buffer_size, "%s.s%dp", base_filename, num_ports);
    if (written < 0 || (size_t)written >= buffer_size) {
        return -1;
    }
    
    return 0;
}

bool touchstone_validate_sparams(const SParameterSet* sparams) {
    if (!sparams || !sparams->data) {
        return false;
    }
    
    if (sparams->num_ports < 1 || sparams->num_frequencies < 1) {
        return false;
    }
    
    // Validate data consistency
    for (int i = 0; i < sparams->num_frequencies; i++) {
        if (!sparams->data[i].s_matrix) {
            return false;
        }
        if (sparams->data[i].num_ports != sparams->num_ports) {
            return false;
        }
    }
    
    return true;
}

int touchstone_export_file(
    const SParameterSet* sparams,
    const char* filename,
    const touchstone_export_options_t* options
) {
    if (!sparams || !filename) {
        return -1;
    }
    
    if (!touchstone_validate_sparams(sparams)) {
        return -1;
    }
    
    // Get options (use defaults if NULL)
    touchstone_export_options_t opts = options ? *options : touchstone_get_default_options();
    
    FILE* fp = fopen(filename, "w");
    if (!fp) {
        return -1;
    }
    
    // Write header line
    // Format: # [FREQ_UNIT] S [DATA_FORMAT] R [REF_IMPEDANCE]
    fprintf(fp, "# %s S %s R %.6e\n",
            get_freq_unit_string(opts.freq_unit),
            get_format_string(opts.data_format),
            opts.reference_impedance);
    
    // Write comments if enabled
    if (opts.include_comments) {
        if (opts.description) {
            fprintf(fp, "! %s\n", opts.description);
        }
        fprintf(fp, "! Touchstone file generated by PulseMoM\n");
        fprintf(fp, "! Number of ports: %d\n", sparams->num_ports);
        fprintf(fp, "! Number of frequency points: %d\n", sparams->num_frequencies);
        
        if (opts.include_port_names && sparams->port_names) {
            for (int i = 0; i < sparams->num_ports; i++) {
                if (sparams->port_names[i]) {
                    fprintf(fp, "! Port %d: %s\n", i + 1, sparams->port_names[i]);
                }
            }
        }
        
        fprintf(fp, "!\n");
    }
    
    // Write data
    const char* format_str = (opts.precision == 6) ? "%.6e" : 
                             (opts.precision == 9) ? "%.9e" : "%.6e";
    
    for (int freq_idx = 0; freq_idx < sparams->num_frequencies; freq_idx++) {
        const SParameterData* data = &sparams->data[freq_idx];
        
        // Convert frequency to requested unit
        double freq = convert_frequency(data->frequency, opts.freq_unit);
        fprintf(fp, format_str, freq);
        
        // Write S-parameters in row-major order (Touchstone standard)
        // Format: S11 S21 S31 ... S12 S22 S32 ... etc.
        for (int j = 0; j < sparams->num_ports; j++) {
            for (int i = 0; i < sparams->num_ports; i++) {
                int idx = i * sparams->num_ports + j;  // Column-major to row-major
                sparameter_complex_t s_ij = data->s_matrix[idx];
                
                switch (opts.data_format) {
                    case TOUCHSTONE_FORMAT_MA: {
                        double mag = SPARAM_ABS(s_ij);
                        double angle_deg = SPARAM_ARG(s_ij) * 180.0 / M_PI;
                        fprintf(fp, " %.6e %.6e", mag, angle_deg);
                        break;
                    }
                    case TOUCHSTONE_FORMAT_DB: {
                        double mag = SPARAM_ABS(s_ij);
                        double db = (mag > 0) ? 20.0 * log10(mag) : -200.0;
                        double angle_deg = SPARAM_ARG(s_ij) * 180.0 / M_PI;
                        fprintf(fp, " %.6e %.6e", db, angle_deg);
                        break;
                    }
                    case TOUCHSTONE_FORMAT_RI: {
                        double real = SPARAM_REAL(s_ij);
                        double imag = SPARAM_IMAG(s_ij);
                        fprintf(fp, " %.6e %.6e", real, imag);
                        break;
                    }
                }
            }
        }
        fprintf(fp, "\n");
    }
    
    fclose(fp);
    return 0;
}

int touchstone_export_mixed_mode(
    const MixedModeSParameters* mixed_mode,
    const char* filename_base,
    const touchstone_export_options_t* options
) {
    if (!mixed_mode || !filename_base) {
        return -1;
    }
    
    int result = 0;
    char filename[512];
    
    // Export differential mode
    if (mixed_mode->differential) {
        snprintf(filename, sizeof(filename), "%s_diff.s%dp",
                filename_base, mixed_mode->differential->num_ports);
        if (touchstone_export_file(mixed_mode->differential, filename, options) != 0) {
            result = -1;
        }
    }
    
    // Export common mode
    if (mixed_mode->common) {
        snprintf(filename, sizeof(filename), "%s_common.s%dp",
                filename_base, mixed_mode->common->num_ports);
        if (touchstone_export_file(mixed_mode->common, filename, options) != 0) {
            result = -1;
        }
    }
    
    // Export mixed-mode conversion terms
    if (mixed_mode->mixed) {
        snprintf(filename, sizeof(filename), "%s_mixed.s%dp",
                filename_base, mixed_mode->mixed->num_ports);
        if (touchstone_export_file(mixed_mode->mixed, filename, options) != 0) {
            result = -1;
        }
    }
    
    return result;
}
