function spice_grid_vf_mna(Rgrid,Lgrid, Rvfit3,Lvfit3, Ggrid,Cgrid, ...
    Rrod_dc,Crod_dc, brn_name_grid, nod_sta_grid, nod_end_grid, nod_grid, ...
    brn_out_grid, nod_out_grid, Rsoil, fpath_grid, fname_grid, flag_Rg)
%  Function:       spice_grid_vf_mna
%  Description:    Generate the spice netlist for built PEEC grid network.
%                  Vector fitting is added as in "Systematic development of
%                  transmission-line models for interconnects with
%                  frequency-dependent losses"
%                  1. header and output node
%                  2. network
%                        -  1. only full L  ( 0Vdc + L )
%                              - 1.a  measurment branch ( 0Vdc + L )
%                              - 1.b  no measurment( L )
%
%                        -  2. self R + full L (R + 0Vdc + L)
%                              - 1.a  measurment branch  (R + 0Vdc + L )
%                              - 1.b  no measurment ( R + L )
%
%                        -  3. self R + mutual R + full L
%                              (R + 0Vdc + E1+E2+...+ L)
%                              - 1.a  measurment branch (R + 0Vdc + E1+E2+...+ L)
%                              - 1.b  no measurment (R + E1+E2+...+ L)
%                  3. end of netlist
%  Calls:
%
%  Input:          Rmtx  --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lmtx  --  L matrix calculated using PEEC (N*N)(H)
%                  bran_name  --  branch name of all conductors
%                  bran_type  --  branch type of all conductors(measurmnt or not)
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  output     --  output node and branch name (measurment
%                                 of branch current will be transformed to
%                                 equivalent node voltage)
%                  Nbran      --  num. of branch
%                  Noutput    --  num. of output (all in node style)
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2014-12-24
%  History:

err_ML = 1e-3;

err_fit = 1e-10;

% fprinf doesnot support sparse matrix, thus change sparse matrix
Rgrid = full(Rgrid);
Lgrid = full(Lgrid);


% dfit3 = full(dfit3);
% efit3 = full(efit3);
% rfit3 = full(rfit3);
% pfit3 = full(pfit3);

id_bran_out = find(brn_out_grid);
Nbran     = size(Lgrid,1);
Nbran_out_grid = length(id_bran_out);
Nnod     = size(Cgrid,1);
Nnod_out_grid  = size(nod_out_grid,1);

fname_grid = [fname_grid,'_grid'];

%% 1. Write the head of netlist (external port)
if length(fname_grid)>=4
    if strcmp(fname_grid(end-3:end),'.cir') || strcmp(fname_grid(end-3:end),'.CIR')
        fname_grid(end-3:end) = [];
    end
end
fid = fopen([fpath_grid, fname_grid,'.cir'],'w+');

fprintf(fid,'.SUBCKT %s ', fname_grid);
% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
for ik = 1:Nnod_out_grid
    fprintf(fid,'%s ',nod_out_grid(ik,:));
    if mod(ik,5)==0 && ik~=Nnod_out_grid
        fprintf(fid,'\n+ ');
    end
end

if Nnod_out_grid>0 && Nbran_out_grid>0
    fprintf(fid,'\n+ ');
end

for ik = 1:Nbran_out_grid
    fprintf(fid,'%s ',brn_name_grid(id_bran_out(ik),:));
    if mod(ik,5)==0 && ik~=Nbran_out_grid
        fprintf(fid,'\n+ ');
    end
end
fprintf(fid,'\n');

%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');

%% 3. Write Circuit Network
NR = 0;
NL = 0;
NC = 0;
NK = 0;
NM = 0; % no. of current measurment branch
NV = 0; % no. of vector fitting node


%% 3.a Zn element
Ls = zeros(Nbran,1);
Ls(1:Nbran) = diag(Lgrid);
cofK = zeros(Nbran,1);

if Nbran > 1
    for ik = 1:Nbran
        
        Nfit_grid = find(Rvfit3(ik,:), 1, 'last');
        
        fprintf(fid,'* *  Branch  %s - %s \n', nod_sta_grid(ik,:), nod_end_grid(ik,:));
        
        % self R + full L (R + 0Vdc + L)
        % R - 2-a, 2-b use the same R writing part
        Rtmp = max(Rgrid(ik,ik), 1e-6);
        %nodR = ['nR_', num2str(ik)];
        NR = NR+1;
        fprintf(fid,'R_R%d  %s  nR_%d  %em  TC=0,0 \n', ...
            NR, nod_sta_grid(ik,:), ik, Rtmp*1e3);
        
        % 2-a. with current measurment
        if ~isempty(brn_out_grid) && ...
                ismember(brn_name_grid(ik,:),brn_out_grid,'rows')
            
            % add current measurment block
            NM = NM+1;
            %nodM = ['nM_' num2str(ik)];
            fprintf(fid,'*  Mearsure Branch Current %s \n', brn_name_grid(ik,:));
            % 0V Vdc
            fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
            % H (CCVS for measuring current)
            fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, brn_name_grid(ik,:), NM);
            fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, brn_name_grid(ik,:));
            %nodL1 = nodM;
            
            if Nfit_grid>0
                % add vector fitting equivalent circuit
                vfcplx_flag = Nfit_grid+1;
                
                for ih = 1:Nfit_grid
                    if ih == 1
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*Rvfit3(ik,ih));
                            fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                                NV, ik, NV, 1e6*Lvfit3(ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ih);
                            R2 = Rvfit3(ik,ih+1);
                            L1 = Lvfit3(ik,ih);
                            L2 = Lvfit3(ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %em  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                                NV, ik, NV, 1e6*LC);
                        end
                    elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rvfit3(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                NV, NV-1, NV, 1e6*Lvfit3(ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ih);
                            R2 = Rvfit3(ik,ih+1);
                            L1 = Lvfit3(ik,ih);
                            L2 = Lvfit3(ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                NV, NV-1, NV, 1e6*LC);
                        end
                    end
                    
                end
                
                % L
                NL = NL+1;
                fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                    NL, NV, nod_end_grid(ik,:), 1e6*Ls(ik));
            else
                
                % L
                NL = NL+1;
                fprintf(fid,'L_L%d  nM_%d  %s  %euH \n', ...
                    NL, ik, nod_end_grid(ik,:), 1e6*Ls(ik));
            end
            
            % 2-b. no current measurment
        else
            if Nfit_grid>0
                
                vfcplx_flag = Nfit_grid+1;
                
                % add vector fitting equivalent circuit
                for ih = 1:Nfit_grid
                    
                    if ih == 1
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*Rvfit3(ik,ih));
                            fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                                NV, ik, NV, 1e6*Lvfit3(ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ih);
                            R2 = Rvfit3(ik,ih+1);
                            L1 = Lvfit3(ik,ih);
                            L2 = Lvfit3(ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %em  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                                NV, ik, NV, 1e6*LC);
                        end
                        
                    elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rvfit3(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                NV, NV-1, NV, 1e6*Lvfit3(ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ih);
                            R2 = Rvfit3(ik,ih+1);
                            L1 = Lvfit3(ik,ih);
                            L2 = Lvfit3(ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                NV, NV-1, NV, 1e6*LC);
                        end
                        
                    end
                end
                
                %nodL1 = nodR;
                NL = NL+1;
                fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                    NL, NV, nod_end_grid(ik,:), 1e6*Ls(ik));
            else
                
                NL = NL+1;
                fprintf(fid,'L_L%d  nR_%d  %s  %euH \n', ...
                    NL, ik, nod_end_grid(ik,:), 1e6*Ls(ik));
            end
        end
        
        %% K -- 2-a, 2-b use the same K writing part
        cofK(ik+1:Nbran) = Lgrid(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
        for ih = ik+1:Nbran
            if cofK(ih) > 1
                cofK(ih) = 0.99;
            elseif cofK(ih) < -1
                cofK(ih) = -0.99;
            end
            
            if abs(cofK(ih)) > err_ML
                NK = NK+1;
                fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                    NK, ik, ih, cofK(ih));
            end
        end
        
    end
    
elseif Nbran==1
    %% R - 2-a, 2-b use the same R writing part
    
    Nfit_grid = find(Rvfit3(ik,:), 1, 'last');
    
    fprintf(fid,'R_R%d  %s  nR_%d  %em  TC=0,0 \n', 1, nod_sta_grid(1,:), 1, Rgrid(1,1)*1e3);
    
    %% 2-a. with current measurment
    if ~isempty(brn_out_grid) && ...
            ismember(brn_name_grid(1,:),brn_out_grid,'rows')
        
        % add current measurment block
        %nodM = ['nM_' num2str(ik)];
        fprintf(fid,'*  Mearsure Branch Current %s \n',brn_name_grid(1,:));
        % 0V Vdc
        fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', 1, 1, 1);
        % H (CCVS for measuring current)
        fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', 1, brn_name_grid(1,:), 1);
        fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', 1, brn_name_grid(1,:));
        %nodL1 = nodM;
        
        if Nfit_grid>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit_grid+1;
            
            for ih = 1:Nfit_grid
                
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rvfit3(ik,ih));
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*Lvfit3(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                    
                elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rvfit3(ik,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*Lvfit3(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', NL, NV, nod_end_grid(1,:), 1e6*Ls(1));
        else
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %euH \n', NL, 1, nod_end_grid(1,:), 1e6*Ls(1));
            
        end
        %% 2-b. no current measurment
    else
        Nfit_grid = find(Rvfit3(1,:), 1, 'last');
        %nodL1 = nodR;
        if Nfit_grid>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit_grid+1;
            
            for ih = 1:Nfit_grid
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rvfit3(1,ih));
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*Lvfit3(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                    
                elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rvfit3(1,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*Lvfit3(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', NL, NV, nod_end_grid(1,:), 1e6*Ls(1));
        else
            
            fprintf(fid,'L_L%d  nR_%d  %s  %euH \n', NL, 1, nod_end_grid(1,:), 1e6*Ls(1));
        end
    end
    
end


%% 3.b Yn off diagonal element
for ik = 1:Nnod-1
    fprintf(fid,'*  Node  %s  to other nodes\n', nod_grid(ik,:));
    
    for ig = ik+1:Nnod
        fprintf(fid,'* *  Node  %s  to  Node  %s  \n', nod_grid(ik,:),nod_grid(ig,:));
        
        Rtmp = -1/Ggrid(ik,ig);
        Ctmp = -Cgrid(ik,ig);
        
        %         NR = NR+1;
        %         fprintf(fid,'R_R%d  %s  %s  %em  TC=0,0 \n', ...
        %             NR, nod_grid(ik,:), nod_grid(ig,:), Rtmp*1e3);
        
        if (Ctmp)>1e-8
            NC = NC+1;
            fprintf(fid,'C_C%d  %s  %s  %euF \n', ...
                NC, nod_grid(ik,:), nod_grid(ig,:), 1e6*Ctmp);
        elseif (Ctmp)>1e-12
            NC = NC+1;
            fprintf(fid,'C_C%d  %s  %s  %epF \n', ...
                NC, nod_grid(ik,:), nod_grid(ig,:), 1e9*Ctmp);
        end
        
    end
end


%% 3.b Write the GND node
% Adding nonlinear ground resistance modeling soil ionization effect
E0 = 350e3;  % E = 350kV/m
RGname =[fname_grid,'_Ri',];
NRG = 0;

for ik = 1:Nnod
    fprintf(fid,'* *  Node %s to ground \n', nod_grid(ik,:));
    
    NRG = NRG+1;
    
    dum=Ggrid(ik,:);dum(ik)=0;
    D = Ggrid(ik,ik)+sum(dum);
    % replace by the nonlinear Rg
    Rgrod = 1/D;
    if Rgrod<0
        Rgrod = Rrod_dc(ik);
    elseif Rgrod>2*Rrod_dc(ik)
        Rgrod = Rrod_dc(ik);
    end
    
    if flag_Rg == 0
        if Rgrod~=0
            fprintf(fid,'R_R%s  %s  0  %e  TC=0,0 \n', ...
                nod_grid(ik,:), nod_grid(ik,:), Rgrod);
        end
    elseif flag_Rg == 1
        
        Ig = 1/(2*pi)*E0*Rsoil/(Rgrod^2);
        fprintf(fid,'X_G%s  %s  %s  PARAMS: Ig=%e  R0=%e \n', ...
            nod_grid(ik,:), nod_grid(ik,:), RGname, Ig, Rgrod);
    end
    
    dum=Cgrid(ik,:);dum(ik)=0;
    C0 = Cgrid(ik,ik)+sum(dum);
    
    if C0>1e-8
        NC = NC+1;
        fprintf(fid,'C_C%s  %s  0  %euF \n', nod_grid(ik,:), nod_grid(ik,:), C0*1e6);
    elseif C0>1e-12
        NC = NC+1;
        fprintf(fid,'C_C%s  %s  0  %epF \n', nod_grid(ik,:), nod_grid(ik,:), C0*1e9);
    elseif C0<0 && abs(C0)>1e-8
        NC = NC+1;
        fprintf(fid,'C_C%s  %s  0  %euF \n', nod_grid(ik,:), nod_grid(ik,:), Crod_dc(ik)*1e6);
    elseif C0<0 && abs(C0)>1e-12
        NC = NC+1;
        fprintf(fid,'C_C%s  %s  0  %epF \n', nod_grid(ik,:), nod_grid(ik,:), Crod_dc(ik)*1e9);
    end
    
end

fprintf(fid,'.ENDS %s \n', fname_grid);


%% 4. Adding nonlinear ground resistance
if flag_Rg == 1
    % single rod inozation model
    fprintf(fid,'* Nonlinear Ground Resistance Used in Ground Grid\n');
    fprintf(fid,'.SUBCKT  %s  1  PARAMS: Ig=1000  R0=20 \n', RGname);
    fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
    fprintf(fid,'V_I_SENSE  2  3  0V \n');
    fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
    fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
    fprintf(fid,'E_VAR  3  0 \n');
    fprintf(fid,'+  VALUE={V(4)*R0/SQRT(1+ABS(V(4))/Ig)} \n');
    fprintf(fid,'.ENDS %s \n', RGname);
end


%% close the file after writing the spice file
fclose(fid);


end


