function spice_grid_y_mtx_vf_na(dfit3,efit3,rfit3,pfit3, nod_grid, re,len,depth, ...
    nod_out_grid, Rsoil, fpath_grid, fname_grid, flag_ver)
%  Function:       spice_grid_y_mtx_vf_na
%  Description:    Generate the spice netlist for built PEEC grid network.
%                  Vector fitting is added as in "Systematic development of
%                  transmission-line models for interconnects with
%                  frequency-dependent losses"
%                  1. header and output node
%                  2. network
%                        -  1. only full L  ( 0Vdc + L )
%                              - 1.a  measurment branch ( 0Vdc + L )
%                              - 1.b  no measurment( L )
%
%                        -  2. self R + full L (R + 0Vdc + L)
%                              - 1.a  measurment branch  (R + 0Vdc + L )
%                              - 1.b  no measurment ( R + L )
%
%                        -  3. self R + mutual R + full L
%                              (R + 0Vdc + E1+E2+...+ L)
%                              - 1.a  measurment branch (R + 0Vdc + E1+E2+...+ L)
%                              - 1.b  no measurment (R + E1+E2+...+ L)
%                  3. end of netlist
%  Calls:
%
%  Input:          Rmtx  --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lmtx  --  L matrix calculated using PEEC (N*N)(H)
%                  bran_name  --  branch name of all conductors
%                  bran_type  --  branch type of all conductors(measurmnt or not)
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  output     --  output node and branch name (measurment
%                                 of branch current will be transformed to
%                                 equivalent node voltage)
%                  Nbran      --  num. of branch
%                  Noutput    --  num. of output (all in node style)
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2014-12-24
%  History:


err_fit = 1e-10;
% fprinf doesnot support sparse matrix, thus change sparse matrix
dfit3 = full(dfit3);
efit3 = full(efit3);
rfit3 = full(rfit3);
pfit3 = full(pfit3);


Nnod     = size(efit3,1);
Nnod_out_grid  = size(nod_out_grid,1);

fname_grid = [fname_grid,'_grid'];

%% 1. Write the head of netlist (external port)
if length(fname_grid)>=4
    if strcmp(fname_grid(end-3:end),'.cir') || strcmp(fname_grid(end-3:end),'.CIR')
        fname_grid(end-3:end) = [];
    end
end
fid = fopen([fpath_grid, fname_grid,'.cir'],'w+');

fprintf(fid,'.SUBCKT %s ', fname_grid);
% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
for ik = 1:Nnod_out_grid
    fprintf(fid,'%s ',nod_out_grid(ik,:));
    if mod(ik,5)==0 && ik~=Nnod_out_grid
        fprintf(fid,'\n+ ');
    end
end

fprintf(fid,'\n');

%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');

%% 3. Write Circuit Network
NR = 0;
NC = 0;
NV = 0; % no. of vector fitting node

% define the direction of the first condutor as reference direction
% cofLSign = sign(Lmtx(1:Nbran,1));

% off diagonal element
for ik = 1:Nnod-1
    fprintf(fid,'*  Node  %s  to other nodes\n', nod_grid(ik,:));
    
    for ig = ik+1:Nnod
        fprintf(fid,'* *  Node  %s  to  Node  %s  \n', nod_grid(ik,:),nod_grid(ig,:));
        
        Nfit_grid = find(abs(rfit3(ik,ig,:))>err_fit, 1, 'last');
        Nfit_grid = min(Nfit_grid, find(abs(pfit3(ik,ig,:))>err_fit, 1, 'last'));
        
        Rtmp = -1/dfit3(ik,ig);
        Ctmp = -efit3(ik,ig);
        NR = NR+1;
        fprintf(fid,'R_R%d  %s  %s  %em  TC=0,0 \n', ...
            NR, nod_grid(ik,:), nod_grid(ig,:), Rtmp*1e3);
        
        if abs(Ctmp)>1e-12
            NC = NC+1;
            fprintf(fid,'C_C%d  %s  %s  %euF \n', ...
                NC, nod_grid(ik,:), nod_grid(ig,:), 1e6*Ctmp);
        end
        
        % add vector fitting equivalent circuit
        for ih = 1:Nfit_grid
            
            if isreal(rfit3(ik,ig,ih))  % real pole  Yij=-Ymtx(ij)
                NV = NV+1;
                
                rtmp = -rfit3(ik,ig,ih);
                ptmp = pfit3(ik,ig,ih);
                
                Rtmp = -ptmp/rtmp;
                Ltmp = 1/rtmp;
                fprintf(fid,'R_V%d  %s  nV_%d  %em  TC=0,0 \n', ...
                    NV, nod_grid(ik,:), NV, 1e3*Rtmp);
                fprintf(fid,'L_V%d  nV_%d  %s  %euH \n', ...
                    NV, NV, nod_grid(ig,:), 1e6*Ltmp);
                
            else % complex pole.
                ih = ih+1;
                
                r1 = -rfit3(ik,ig,ih-1);
                r2 = -rfit3(ik,ig,ih);
                p1 = pfit3(ik,ig,ih-1);
                p2 = pfit3(ik,ig,ih);
                
                Ltmp = 1/(r1+r2);
                R1tmp = -(r1*p1+r2*p2)*Ltmp^2;
                Ctmp = -1/( (p1-p2)^2*Ltmp^3*r1*r2 );
                R2tmp = -1/( r1/p1+r2/p2 ) - R1tmp;
                
                NV = NV+1;
                fprintf(fid,'R_V%d  %s  nV_%d  %em  TC=0,0 \n', ...
                    NV, nod_grid(ik,:), NV, 1e3*R1tmp);
                NV = NV+1;
                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                    NV, NV-1, NV, 1e6*Ltmp);
                fprintf(fid,'R_V%d  nV_%d  %s  %em  TC=0,0 \n', ...
                    NV, NV, nod_grid(ig,:), 1e3*R2tmp);
                fprintf(fid,'C_V%d  nV_%d  %s  %euF \n', ...
                    NV, NV, nod_grid(ig,:), 1e6*Ctmp);
                
            end
        end
    end
end



%% 3.b Write the GND node
% Adding nonlinear ground resistance modeling soil ionization effect
E0 = 350e3;  % E = 350kV/m
RGname =[fname_grid,'_Ri',];
NRG = 0;

for ik = 1:Nnod
    fprintf(fid,'* *  Node %s to ground \n', nod_grid(ik,:));
    
    NRG = NRG+1;
    
    Nfit_grid = find(abs(rfit3(ik,ik,:))>err_fit, 1, 'last');
    Nfit_grid = min(Nfit_grid, find(abs(pfit3(ik,ik,:))>err_fit, 1, 'last'));

    dum=dfit3(ik,:);dum(ik)=0;
    D = dfit3(ik,ik)+sum(dum);
    
    if flag_ver == 0
        Rgrod = 1/D;  % replace by the nonlinear Rg
        
        if Rgrod~=0
            fprintf(fid,'R_R%s  %s  0  %e  TC=0,0 \n', ...
                nod_grid(ik,:), nod_grid(ik,:), Rgrod);
        end
    elseif flag_ver == 1
        G1tmp = 0;
        for ih = 1:Nfit_grid
            dum=squeeze(rfit3(ik,:,ih));dum(ik)=0;
            r0tmp = rfit3(ik,ik,ih)+sum(dum);
            G1tmp = G1tmp+r0tmp/pfit3(ik,ik,ih);
        end
        G0tmp = D-G1tmp;
        
        Rgrod = 1/G0tmp;  % replace by the nonlinear Rg
        %Rgrod = 18.6727;
        Ig = 1/(2*pi)*E0*Rsoil/(Rgrod);
        
        if G1tmp~=0
            fprintf(fid,'R_R%s  %s  0  %em  TC=0,0 \n', nod_grid(ik,:), nod_grid(ik,:), 1/G1tmp*1e3);
        end
        fprintf(fid,'X_G%s  %s  %s  PARAMS: Ig=%e  R0=%e \n', ...
            nod_grid(ik,:), nod_grid(ik,:), RGname, Ig, Rgrod);
        
    elseif flag_ver == 2
        Rcof = Rsoil/(2*pi*len(ik));
        %Imin = E0/(Rcof*re(ik));
        fprintf(fid,'X_G%s  %s  %s  PARAMS: RCOF=%.4e  E0=%.2fk  LEN=%.2e  RE=%.4fm \n', ...
            nod_grid(ik,:), nod_grid(ik,:), RGname, Rcof, E0/1e3,len(ik),re(ik)*1e3);    
    elseif flag_ver == 3
        Rcof = Rsoil/(2*pi*len(ik));
        fprintf(fid,'X_G%s  %s  %s  PARAMS: RCOF=%.4e  E0=%.2fk  LEN=%.2e  RE=%.4fm  DEPTH=%.4e \n', ...
            nod_grid(ik,:), nod_grid(ik,:), RGname, Rcof, E0/1e3,len(ik),re(ik)*1e3, depth(ik));    
    end
    
    dum=efit3(ik,:);dum(ik)=0;
    C0 = efit3(ik,ik)+sum(dum);
    if abs(C0)>1e-12
        NC = NC+1;
        fprintf(fid,'C_C%s  %s  0  %euF \n', nod_grid(ik,:), nod_grid(ik,:), C0*1e6);
    end
    % add vector fitting equivalent circuit
    for ih = 1:Nfit_grid
        
        if isreal(rfit3(ik,ik,ih))  % real pole
            NV = NV+1;
            
            dum=squeeze(rfit3(ik,:,ih));dum(ik)=0;
            rtmp = rfit3(ik,ik,ih)+sum(dum);
            Rtmp = -pfit3(ik,ik,ih)/rtmp;
            Ltmp = 1/rtmp;
            fprintf(fid,'R_V%d  %s  nV_%d  %em  TC=0,0 \n', ...
                NV, nod_grid(ik,:), NV, 1e3*Rtmp);
            fprintf(fid,'L_V%d  nV_%d  0  %euH \n', ...
                NV, NV, 1e6*Ltmp);
            
        else % complex pole.
            ih = ih+1;
            
            dum=squeeze(rfit3(ik,:,ih-1));dum(ik)=0;
            rtmp1 = rfit3(ik,ik,ih-1)+sum(dum);
            dum=squeeze(rfit3(ik,:,ih));dum(ik)=0;
            rtmp2 = rfit3(ik,ik,ih)+sum(dum);
            r1 = rtmp1;
            r2 = rtmp2;
            p1 = pfit3(ik,ik,ih-1);
            p2 = pfit3(ik,ik,ih);
            
            Ltmp = 1/(r1+r2);
            R1tmp = -(r1*p1+r2*p2)*Ltmp^2;
            Ctmp = -1/( (p1-p2)^2*Ltmp^3*r1*r2 );
            R2tmp = -1/( r1/p1+r2/p2 ) - R1tmp;
            
            NV = NV+1;
            fprintf(fid,'R_V%d  %s  nV_%d  %em  TC=0,0 \n', ...
                NV, nod_grid(ik,:), NV, 1e3*R1tmp);
            NV = NV+1;
            fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                NV, NV-1, NV, 1e6*Ltmp);
            fprintf(fid,'R_V%d  nV_%d  0  %em  TC=0,0 \n', ...
                NV, NV, 1e3*R2tmp);
            fprintf(fid,'C_V%d  nV_%d  0  %euF \n', ...
                NV, NV, 1e6*Ctmp);
        end
    end
end

fprintf(fid,'.ENDS %s \n', fname_grid);

%% 4. Adding nonlinear ground resistance
if flag_ver == 1 % single rod inozation model
    fprintf(fid,'* Nonlinear Ground Resistance Used in Ground Grid\n');
    fprintf(fid,'.SUBCKT  %s  1  PARAMS: Ig=1000  R0=20 \n', RGname);
    fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
    fprintf(fid,'V_I_SENSE  2  3  0V \n');
    fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
    fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
    fprintf(fid,'E_VAR  3  0 \n');
    %fprintf(fid,'+  VALUE={V(4)*R0/SQRT(1+ABS(V(4))/Ig)} \n');
    %fprintf(fid,'+  VALUE={V(4)*R0/(1+ABS(V(4))/Ig)} \n');
    fprintf(fid,'+  VALUE={V(4)*R0/(1+SQRT(ABS(LOG(ABS(V(4))/Ig))))} \n');
    fprintf(fid,'.ENDS %s \n', RGname);
elseif flag_ver == 2  % equivalent radius rod inozation model (Vertical Rod)
    fprintf(fid,'* Vertical Nonlinear Ground Resistance Used in Ground Grid\n');
    fprintf(fid,'.SUBCKT  %s  1  PARAMS: RCOF=2 E0=350e3 LEN=5 RE=5m \n', RGname);
    fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
    fprintf(fid,'V_I_SENSE  2  3  0V \n');
    fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
    fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
    fprintf(fid,'E_VAR  3  0 \n');
    %fprintf(fid,'+  VALUE={V(4)*(LOG(4*LEN/(LIMIT(ABS(V(4)),IMIN,1G)*RCOF/E0))-1)*RCOF} \n');
    %fprintf(fid,'+  VALUE={V(4)*(LOG(4*LEN/LIMIT(ABS(V(4))*RCOF/E0,RE,1.2*LEN))-1)*RCOF} \n');
    %fprintf(fid,'+  VALUE={V(4)*RCOF*(LOG(LEN/LIMIT(ABS(V(4))*RCOF/E0,RE,LEN)+1))} \n');
    fprintf(fid,'+  VALUE={V(4)*RCOF*(LOG(LEN/LIMIT(ABS(V(4))*RCOF/E0,RE,LEN))+1)} \n');
    % log(l/r)+1 not as in papers
    fprintf(fid,'.ENDS %s \n', RGname);
elseif flag_ver == 3  % equivalent radius rod inozation model (Horizontal)
    fprintf(fid,'* Horizontal Nonlinear Ground Resistance Used in Ground Grid\n');
    fprintf(fid,'.SUBCKT  %s  1  PARAMS: RCOF=2 E0=350e3 LEN=5 RE=5m DEPTH=0.5 \n', RGname);
    fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
    fprintf(fid,'V_I_SENSE  2  3  0V \n');
    fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
    fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
    fprintf(fid,'E_VAR  3  0 \n');
    %fprintf(fid,'+  VALUE={V(4)*(LOG(2*LEN*LEN/(LIMIT(ABS(V(4))*RCOF/E0,RE,0.25*LEN*LEN/DEPTH)*DEPTH)-2))*RCOF} \n');
    fprintf(fid,'+  VALUE={V(4)*RCOF*(LOG(LEN*LEN/(2*LIMIT(ABS(V(4))*RCOF/E0,RE,LEN*LEN/DEPTH)*DEPTH))+0.48)} \n');
    %fprintf(fid,'+  VALUE={V(4)*(LOG(2*LEN/(LIMIT(ABS(V(4))*RCOF/E0,RE,0.25*LEN*LEN/DEPTH)*DEPTH)-1))*RCOF} \n');
    fprintf(fid,'.ENDS %s \n', RGname);
end

%% close the file after writing the spice file
fclose(fid);


end


