function spice_grid_self_vf(Rgrid,Lgrid, Ggrid,Cgrid, Rfit_grid, Lfit_grid,  ...
    bran_name_grid, nod_start_grid, nod_end_grid, nod_grid, ...
    bran_out_grid, nod_out_grid, R_soil, fpath_grid, fname_grid, flag_Rg)
%  Function:       spice_grid_self_vf
%  Description:    Generate the spice netlist for built PEEC grid network.
%                  Vector fitting is added as in "Systematic development of
%                  transmission-line models for interconnects with
%                  frequency-dependent losses"
%                  1. header and output node
%                  2. network
%                        -  1. only full L  ( 0Vdc + L )
%                              - 1.a  measurment branch ( 0Vdc + L )
%                              - 1.b  no measurment( L )
%
%                        -  2. self R + full L (R + 0Vdc + L)
%                              - 1.a  measurment branch  (R + 0Vdc + L )
%                              - 1.b  no measurment ( R + L )
%
%                        -  3. self R + mutual R + full L
%                              (R + 0Vdc + E1+E2+...+ L)
%                              - 1.a  measurment branch (R + 0Vdc + E1+E2+...+ L)
%                              - 1.b  no measurment (R + E1+E2+...+ L)
%                  3. end of netlist
%  Calls:
%
%  Input:          Rmtx  --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lmtx  --  L matrix calculated using PEEC (N*N)(H)
%                  bran_name  --  branch name of all conductors
%                  bran_type  --  branch type of all conductors(measurmnt or not)
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  output     --  output node and branch name (measurment
%                                 of branch current will be transformed to
%                                 equivalent node voltage)
%                  Nbran      --  num. of branch
%                  Noutput    --  num. of output (all in node style)
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2014-12-24
%  History:


err_ML = 1e-3;
err_MR = 1e-6;

% fprinf doesnot support sparse matrix, thus change sparse matrix
Rgrid = full(Rgrid);
Lgrid = full(Lgrid);
Rfit_grid = full(Rfit_grid);
Lfit_grid = full(Lfit_grid);
Ggrid = full(Ggrid);


Nbran     = size(Lgrid,1);
Nbran_out_grid = size(bran_out_grid,1);
Nnod_out_grid  = size(nod_out_grid,1);
Nnod_gnd_grid  = size(nod_grid,1);

fname_grid = [fname_grid,'_grid'];

%% 1. Write the head of netlist (external port)
fid = fopen([fpath_grid, fname_grid,'.cir'],'w+');

fprintf(fid,'.SUBCKT %s ', fname_grid);
% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
for ik = 1:Nnod_out_grid
    fprintf(fid,'%s ', deblank(nod_out_grid(ik,:)));
    if mod(ik,5)==0 && ik~=Nnod_out_grid
        fprintf(fid,'\n+ ');
    end
end

if Nnod_out_grid>0 && Nbran_out_grid>0
    fprintf(fid,'\n+ ');
end

for ik = 1:Nbran_out_grid
    fprintf(fid,'%s ', deblank(bran_out_grid(ik,:)));
    if mod(ik,5)==0 && ik~=Nbran_out_grid
        fprintf(fid,'\n+ ');
    end
end
fprintf(fid,'\n');

%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');


%% 3. Write Circuit Network
NR = 0;
NL = 0;
NK = 0;
NC = 0;
NE = 0; % no. of added point for E (used for mutual R)
NM = 0; % no. of current measurment branch
NV = 0; % no. of vector fitting node
%vfcplx_flag = 0;% flag of vector fitting complex node

Ls = zeros(Nbran,1);
Ls(1:Nbran) = diag(Lgrid);

% define the direction of the first condutor as reference direction
% cofLSign = sign(Lmtx(1:Nbran,1));

cofK = zeros(Nbran,1);
cofMR = zeros(Nbran,1);

if Nbran > 1
    for ik = 1:Nbran
        
        idRsM = abs(Rgrid(ik+1:end,ik)) > 0;
        flgRm = sum(idRsM);

        Nfit_grid = find(Rfit_grid(ik,:), 1, 'last');
        
        fprintf(fid,'* *  Branch  %s - %s \n', ...
            deblank(nod_start_grid(ik,:)), deblank(nod_end_grid(ik,:)));
        
        %% (1). self R + full L (R + 0Vdc + L)
        if flgRm==0
            
            %% R - 2-a, 2-b use the same R writing part
            Rtmp = max(Rgrid(ik,ik), 1e-6);
            %nodR = ['nR_', num2str(ik)];
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %em  TC=0,0 \n', ...
                NR, deblank(nod_start_grid(ik,:)), ik, Rtmp*1e3);
            
            %% 2-a. with current measurment
            if ~isempty(bran_out_grid) && ...
                ismember(bran_name_grid(ik,:),bran_out_grid,'rows')
                
                % add current measurment block
                NM = NM+1;
                %nodM = ['nM_' num2str(ik)];
                fprintf(fid,'*  Mearsure Branch Current %s \n', deblank(bran_name_grid(ik,:)));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, deblank(bran_name_grid(ik,:)), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, deblank(bran_name_grid(ik,:)));
                %nodL1 = nodM;
                
                if Nfit_grid>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit_grid+1;
                    
                    for ih = 1:Nfit_grid
                        if ih == 1 
                            NV = NV+1;
                            
                            if isreal(Rfit_grid(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rfit_grid(ik,ih));
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                                    NV, ik, NV, 1e6*Lfit_grid(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit_grid(ik,ih);
                                R2 = Rfit_grid(ik,ih+1);
                                L1 = Lfit_grid(ik,ih);
                                L2 = Lfit_grid(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %em  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                                    NV, ik, NV, 1e6*LC);
                            end
                        elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                            NV = NV+1;

                            if isreal(Rfit_grid(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit_grid(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit_grid(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit_grid(ik,ih);
                                R2 = Rfit_grid(ik,ih+1);
                                L1 = Lfit_grid(ik,ih);
                                L2 = Lfit_grid(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                        
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                        NL, NV, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nM_%d  %s  %euH \n', ...
                        NL, ik, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                end
                
                
                %% 2-b. no current measurment
            else
                if Nfit_grid>0
                    
                    vfcplx_flag = Nfit_grid+1;
                    
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit_grid

                        if ih == 1
                            NV = NV+1;
                            
                            if isreal(Rfit_grid(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rfit_grid(ik,ih));
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                                    NV, ik, NV, 1e6*Lfit_grid(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit_grid(ik,ih);
                                R2 = Rfit_grid(ik,ih+1);
                                L1 = Lfit_grid(ik,ih);
                                L2 = Lfit_grid(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %em  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                                    NV, ik, NV, 1e6*LC);
                            end
                            
                        elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                            NV = NV+1;

                            if isreal(Rfit_grid(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit_grid(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit_grid(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit_grid(ik,ih);
                                R2 = Rfit_grid(ik,ih+1);
                                L1 = Lfit_grid(ik,ih);
                                L2 = Lfit_grid(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                            
                        end
                    end
                    
                    %nodL1 = nodR;
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                        NL, NV, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                else
                    
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nR_%d  %s  %euH \n', ...
                        NL, ik, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                end
                
            end
            
            %% K -- 2-a, 2-b use the same K writing part
            cofK(ik+1:Nbran) = Lgrid(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
                end
            end
            
            
            %% (2). self R + mutual R + full L (R + 0Vdc + E1+E2+...+ L)
        elseif  flgRm>0
            
            %% R -- 3-a, 3-b use the same R writing part
            Rtmp = max(Rgrid(ik,ik), 1e-6);
            %nodR = ['nR_', num2str(ik)];
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %em  TC=0,0 \n', ...
                NR, deblank(nod_start_grid(ik,:)), ik, Rtmp*1e3);
            
            %% 3-a. with current measurment (R + 0Vdc + E1+E2+...+ L)
            if ~isempty(bran_out_grid) && ...
                ismember(bran_name_grid(ik,:),bran_out_grid,'rows')
                
                % add current measurment block
                %nodM = ['nM_', num2str(ik)];
                NM = NM+1;
                fprintf(fid,'*  Mearsure Branch Current %s \n', deblank(bran_name_grid(ik,:)));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, deblank(bran_name_grid(ik,:)), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, deblank(bran_name_grid(ik,:)));
                
                %nodE0 = nodM;   % first node of E series (mutual R)
                %nodE2 = nodE0;  % initial nodE2 for case of no E exist
                
                % E - mutual R (VCVS)
                cofMR(1:Nbran) = Rgrid(1:Nbran,ik)./Rgrid(ik,ik);
                cofMR(ik) = 0;
                idRsM = find(abs(cofMR) > err_MR);
                NMR = length(idRsM);
                
                for ih = 1:NMR
                    %nodRex = ['nR_', num2str(ind(ih))];
                    if ih==1 %&& ih~=ik % first node is set to be nodE0
                        NE = NE+1;
                        %nodE1 = ['nE_', num2str(NE)];
                        %nodE2 = nodE1;
                        fprintf(fid,'E_E%d  nM_%d  nE_%d  %s  nR_%d  %e \n', ...
                            NE, ik, NE, deblank(nod_start_grid(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    elseif ih>1 %&& ih~=ik
                        NE = NE+1;
                        %nodE1 = ['nE_', num2str(NE-1)];
                        %nodE2 = ['nE_', num2str(NE)];
                        fprintf(fid,'E_E%d  nE_%d  nE_%d  %s  nR_%d  %e \n', ...
                            NE,  NE-1, NE, deblank(nod_start_grid(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    end
                end
                
                if Nfit_grid>0
                    
                    vfcplx_flag = Nfit_grid+1;
                    
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit_grid
                        
                        if ih == 1
                            NV = NV+1;
                            
                            if NMR == 0
                                
                                if isreal(Rfit_grid(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*Rfit_grid(ik,ih));
                                    fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                                        NV, ik, NV, 1e6*Lfit_grid(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit_grid(ik,ih);
                                    R2 = Rfit_grid(ik,ih+1);
                                    L1 = Lfit_grid(ik,ih);
                                    L2 = Lfit_grid(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %em  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                                        NV, ik, NV, 1e6*LC);
                                end
                                
                            elseif NMR >= 1
                                
                                if isreal(Rfit_grid(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*Rfit_grid(ik,ih));
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %euH \n', ...
                                        NV, NE, NV, 1e6*Lfit_grid(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit_grid(ik,ih);
                                    R2 = Rfit_grid(ik,ih+1);
                                    L1 = Lfit_grid(ik,ih);
                                    L2 = Lfit_grid(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nE_%d  nVC_%d  %em  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %euH \n', ...
                                        NV, NE, NV, 1e6*LC);
                                end
                            end
                        elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                            NV = NV+1;

                            if isreal(Rfit_grid(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit_grid(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit_grid(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit_grid(ik,ih);
                                R2 = Rfit_grid(ik,ih+1);
                                L1 = Lfit_grid(ik,ih);
                                L2 = Lfit_grid(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                        NL, NV, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    if NMR == 0
                        fprintf(fid,'L_L%d  nM_%d  %s  %euH \n', ...
                            NL, ik, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                    elseif NMR >= 1
                        fprintf(fid,'L_L%d  nE_%d  %s  %euH \n', ...
                            NL, NE, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                    end
                end
                %% 3-b. no current measurment (R + E1+E2+...+ L)
            else
                %nodE0 = nodR;   % first node of E series (mutual R)
                %nodE2 = nodE0;  % initial nodE2 for case of no E exist
                
                % E - mutual R (VCVS)
                cofMR(1:Nbran) = Rgrid(1:Nbran,ik)./Rgrid(ik,ik);
                cofMR(ik) = 0;
                idRsM = find(abs(cofMR) > err_MR);
                NMR = length(idRsM);
                
                for ih = 1:NMR
                    if ih==1 %&& ih~=ik % first node is set to be nodE0
                        NE = NE+1;
                        fprintf(fid,'E_E%d  nR_%d  nE_%d  %s  nR_%d  %e \n', ...
                            NE, ik, NE, deblank(nod_start_grid(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    elseif ih>1 %&& ih~=ik
                        NE = NE+1;
                        fprintf(fid,'E_E%d  nE_%d  nE_%d  %s  nR_%d  %e \n', ...
                            NE, NE-1, NE, deblank(nod_start_grid(idRsM(ih),:)), idRsM(ih), cofMR(idRsM(ih)));
                    end
                end
                
                if Nfit_grid>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit_grid+1;
                    
                    for ih = 1:Nfit_grid

                        if ih == 1
                            NV = NV+1;
                            
                            if NMR == 0
                                if isreal(Rfit_grid(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*Rfit_grid(ik,ih));
                                    fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                                        NV, ik, NV, 1e6*Lfit_grid(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit_grid(ik,ih);
                                    R2 = Rfit_grid(ik,ih+1);
                                    L1 = Lfit_grid(ik,ih);
                                    L2 = Lfit_grid(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %em  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, ik, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                                        NV, ik, NV, 1e6*LC);
                                end
                                
                            elseif NMR >= 1
                                if isreal(Rfit_grid(ik,ih))  % real pole
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*Rfit_grid(ik,ih));
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %euH \n', ...
                                        NV, NE, NV, 1e6*Lfit_grid(ik,ih));
                                else % complex pole
                                    vfcplx_flag = ih+1;
                                    
                                    R1 = Rfit_grid(ik,ih);
                                    R2 = Rfit_grid(ik,ih+1);
                                    L1 = Lfit_grid(ik,ih);
                                    L2 = Lfit_grid(ik,ih+1);
                                    
                                    LC = L1+L2;
                                    RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                    RC1 = 1 / (1/(R1+R2)-1/RC2);
                                    CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                    
                                    fprintf(fid,'R_VC%d  nE_%d  nVC_%d  %em  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC1);
                                    fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                        NV, NV, NV, 1e6*CC);
                                    fprintf(fid,'R_V%d  nE_%d  nV_%d  %em  TC=0,0 \n', ...
                                        NV, NE, NV, 1e3*RC2);
                                    fprintf(fid,'L_V%d  nE_%d  nV_%d  %euH \n', ...
                                        NV, NE, NV, 1e6*LC);
                                end
                                
                            end
                        elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                            NV = NV+1;

                            if isreal(Rfit_grid(ik,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rfit_grid(ik,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*Lfit_grid(ik,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rfit_grid(ik,ih);
                                R2 = Rfit_grid(ik,ih+1);
                                L1 = Lfit_grid(ik,ih);
                                L2 = Lfit_grid(ik,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                        NL, NV, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    if NMR == 0
                        fprintf(fid,'L_L%d  nR_%d  %s  %euH \n', ...
                            NL, ik, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                    elseif NMR >= 1
                        fprintf(fid,'L_L%d  nE_%d  %s  %euH \n', ...
                            NL, NE, deblank(nod_end_grid(ik,:)), 1e6*Ls(ik));
                    end
                end
            end
            
            %% K -- 3-a, 3-b use the same K writing part
            cofK(ik+1:Nbran) = Lgrid(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
                end
            end
        end
    end
    
elseif Nbran==1
    %% R - 2-a, 2-b use the same R writing part
    
    Nfit_grid = find(Rfit_grid(ik,:), 1, 'last');
    
    fprintf(fid,'R_R%d  %s  nR_%d  %em  TC=0,0 \n', ...
        1, deblank(nod_start_grid(1,:)), 1, Rgrid(1,1)*1e3);
    
    %% 2-a. with current measurment
    if ~isempty(bran_out_grid) && ...
                ismember(bran_name_grid(1,:),bran_out_grid,'rows')
        
        % add current measurment block
        %nodM = ['nM_' num2str(ik)];
        fprintf(fid,'*  Mearsure Branch Current %s \n', deblank(bran_name_grid(1,:)));
        % 0V Vdc
        fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', 1, 1, 1);
        % H (CCVS for measuring current)
        fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', 1, deblank(bran_name_grid(1,:)), 1);
        fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', 1, deblank(bran_name_grid(1,:)));
        %nodL1 = nodM;
        
        if Nfit_grid>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit_grid+1;
            
            for ih = 1:Nfit_grid

                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rfit_grid(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rfit_grid(ik,ih));
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*Lfit_grid(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit_grid(ik,ih);
                        R2 = Rfit_grid(ik,ih+1);
                        L1 = Lfit_grid(ik,ih);
                        L2 = Lfit_grid(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                    
                elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                    NV = NV+1;

                    if isreal(Rfit_grid(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rfit_grid(ik,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*Lfit_grid(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit_grid(ik,ih);
                        R2 = Rfit_grid(ik,ih+1);
                        L1 = Lfit_grid(ik,ih);
                        L2 = Lfit_grid(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                NL, NV, deblank(nod_end_grid(1,:)), 1e6*Ls(1));
        else
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %euH \n', ...
                NL, 1, deblank(nod_end_grid(1,:)), 1e6*Ls(1));
            
        end
        %% 2-b. no current measurment
    else
        Nfit_grid = find(Rfit_grid(1,:), 1, 'last');
        %nodL1 = nodR;
        if Nfit_grid>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit_grid+1;
            
            for ih = 1:Nfit_grid
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rfit_grid(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rfit_grid(1,ih));
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*Lfit_grid(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit_grid(ik,ih);
                        R2 = Rfit_grid(ik,ih+1);
                        L1 = Lfit_grid(ik,ih);
                        L2 = Lfit_grid(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %euH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                    
                elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rfit_grid(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rfit_grid(1,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*Lfit_grid(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rfit_grid(ik,ih);
                        R2 = Rfit_grid(ik,ih+1);
                        L1 = Lfit_grid(ik,ih);
                        L2 = Lfit_grid(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %euF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %em  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %euH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            fprintf(fid,'L_L%d  nV_%d  %s  %euH \n', ...
                NL, NV, deblank(nod_end_grid(1,:)), 1e6*Ls(1));
        else
            
            fprintf(fid,'L_L%d  nR_%d  %s  %euH \n', ...
                NL, 1, deblank(nod_end_grid(1,:)), 1e6*Ls(1));
        end
    end
    
end

%% 3.b Write the GND node
%NC = 0;
if  ~isempty(Cgrid) && isvector(Cgrid)
    for ik = 1:Nnod_gnd_grid
        fprintf(fid,'* *  Node %s to ground \n', deblank(nod_grid(ik,:)));
        if (Cgrid(ik))>1e-8
            fprintf(fid,'C_C%s  %s  0  %euF \n', ...
                deblank(nod_grid(ik,:)), deblank(nod_grid(ik,:)), Cgrid(ik)*1e6);
        elseif (Cgrid(ik))>1e-12
            fprintf(fid,'C_C%s  %s  0  %epF \n', ...
                deblank(nod_grid(ik,:)), deblank(nod_grid(ik,:)), Cgrid(ik)*1e12);
        end
    end
elseif ~isempty(Cgrid) && ismatrix(Cgrid)
    for ik = 1:Nnod_gnd_grid
        fprintf(fid,'* *  Node %s to ground \n', deblank(nod_grid(ik,:)));
        if (Cgrid(ik,ik))>1e-8
            fprintf(fid,'C_C%s  %s  0  %euF \n', ...
                deblank(nod_grid(ik,:)), deblank(nod_grid(ik,:)), Cgrid(ik,ik)*1e6);
        elseif (Cgrid(ik,ik))>1e-12
            fprintf(fid,'C_C%s  %s  0  %epF \n', ...
                deblank(nod_grid(ik,:)), deblank(nod_grid(ik,:)), Cgrid(ik,ik)*1e12);
        end
        
%         for ig = ik+1:Nnod_gnd_grid
%             Cmtmp = -Cgrid(ik,ig);
%             if Cmtmp>1e-8
%                 NC = NC+1;
%                 fprintf(fid,'C_C%d  %s  %s  %euF \n', ...
%                     NC, deblank(nod_grid(ik,:)), deblank(nod_grid(ig,:)), Cmtmp*1e6);
%             elseif Cmtmp>1e-12
%                 NC = NC+1;
%                 fprintf(fid,'C_C%d  %s  %s  %epF \n', ...
%                     NC, deblank(nod_grid(ik,:)), deblank(nod_grid(ig,:)), Cmtmp*1e12);
%             end
%         end
    end
end


%% 4. Adding nonlinear ground resistance modeling soil ionization effect
E0 = 350e3;  % E = 350kV/m
RGname =[fname_grid,'_Ri',];
NRG = 0;
for ik = 1:Nnod_gnd_grid
    fprintf(fid,'* *  Node %s to ground \n', deblank(nod_grid(ik,:)));
    
    NRG = NRG+1;
    
    if isvector(Ggrid) && Ggrid(ik)>1
        Rrod = Ggrid(ik);
    elseif isvector(Ggrid) && Ggrid(ik)<1
        Rrod = 1/Ggrid(ik);
    elseif ismatrix(Ggrid) && Ggrid(ik)>1
        Rrod = Ggrid(ik,ik);
    elseif ismatrix(Ggrid) && Ggrid(ik)<1
        Rrod = 1./Ggrid(ik,ik);
    end
    
    if flag_Rg == 0
        fprintf(fid,'R_R%s  %s  0  %e  TC=0,0 \n', ...
            deblank(nod_grid(ik,:)), deblank(nod_grid(ik,:)), Rrod);
    elseif flag_Rg == 1
        Ig = 1/(2*pi)*E0*R_soil/(Rrod^2);
        fprintf(fid,'X_G%s  %s  %s  PARAMS: Ig=%e  R0=%e \n', ...
            deblank(nod_grid(ik,:)), deblank(nod_grid(ik,:)), RGname, Ig, Rrod);
    end
    
end

fprintf(fid,'.ENDS %s \n', fname_grid);


if flag_Rg == 1
    %% 4. Adding nonlinear ground resistance
    fprintf(fid,'* Nonlinear Ground Resistance Used in Ground Grid\n');
    fprintf(fid,'.SUBCKT  %s  1  PARAMS: Ig=1000  R0=20 \n', RGname);
    fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
    fprintf(fid,'V_I_SENSE  2  3  0V \n');
    fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
    fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
    fprintf(fid,'E_VAR  3  0 \n');
    fprintf(fid,'+  VALUE={V(4)*R0/SQRT(1+ABS(V(4))/{Ig})} \n');
    fprintf(fid,'.ENDS %s \n', RGname); 
end


%% close the file after writing the spice file
fclose(fid);


end


