function spice_subckt_mtx_vf(R0fit3, L0fit3, Rvfit3, Lvfit3,  ...
    bran_name_grid, nod_start_grid, nod_end_grid, ...
    bran_out_grid, nod_out_grid, nod_gnd_grid, Rsoil, fpath_grid, fname_grid)
%  Function:       spice_grid_self_vf
%  Description:    Generate the spice netlist for built PEEC grid network.
%                  Vector fitting is added as in "Systematic development of
%                  transmission-line models for interconnects with
%                  frequency-dependent losses"
%                  1. header and output node
%                  2. network
%                        -  1. only full L  ( 0Vdc + L )
%                              - 1.a  measurment branch ( 0Vdc + L )
%                              - 1.b  no measurment( L )
%
%                        -  2. self R + full L (R + 0Vdc + L)
%                              - 1.a  measurment branch  (R + 0Vdc + L )
%                              - 1.b  no measurment ( R + L )
%
%                        -  3. self R + mutual R + full L
%                              (R + 0Vdc + E1+E2+...+ L)
%                              - 1.a  measurment branch (R + 0Vdc + E1+E2+...+ L)
%                              - 1.b  no measurment (R + E1+E2+...+ L)
%                  3. end of netlist
%  Calls:
%
%  Input:          Rmtx  --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lmtx  --  L matrix calculated using PEEC (N*N)(H)
%                  bran_name  --  branch name of all conductors
%                  bran_type  --  branch type of all conductors(measurmnt or not)
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  output     --  output node and branch name (measurment
%                                 of branch current will be transformed to
%                                 equivalent node voltage)
%                  Nbran      --  num. of branch
%                  Noutput    --  num. of output (all in node style)
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2014-12-24
%  History:


err_fit = 1e-10;
% fprinf doesnot support sparse matrix, thus change sparse matrix
R0fit3 = full(R0fit3);
L0fit3 = full(L0fit3);
Rvfit3 = full(Rvfit3);
Lvfit3 = full(Lvfit3);
Rgrod = diag(R0fit3);
R0fit3 = R0fit3-diag(Rgrod); % replace by the nonlinear Rg


Nbran     = size(L0fit3,1);
Nbran_out_grid = size(bran_out_grid,1);
Nnod_out_grid  = size(nod_out_grid,1);
Nnod_gnd_grid  = size(nod_gnd_grid,1);

fname_grid = [fname_grid,'_grid'];

%% 1. Write the head of netlist (external port)
if length(fname_grid)>=4
    if strcmp(fname_grid(end-3:end),'.cir') || strcmp(fname_grid(end-3:end),'.CIR')
        fname_grid(end-3:end) = [];
    end
end
fid = fopen([fpath_grid, fname_grid,'.cir'],'w+');

fprintf(fid,'.SUBCKT %s ', fname_grid);
% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
for ik = 1:Nnod_out_grid
    fprintf(fid,'%s ',nod_out_grid(ik,:));
    if mod(ik,5)==0 && ik~=Nnod_out_grid
        fprintf(fid,'\n+ ');
    end
end

if Nnod_out_grid>0 && Nbran_out_grid>0
    fprintf(fid,'\n+ ');
end

for ik = 1:Nbran_out_grid
    fprintf(fid,'%s ',bran_out_grid(ik,:));
    if mod(ik,5)==0 && ik~=Nbran_out_grid
        fprintf(fid,'\n+ ');
    end
end
fprintf(fid,'\n');

%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');


%% 3. Write Circuit Network
NR = 0;
NL = 0;
NK = 0;
NE = 0; % no. of added point for E (used for mutual R)
NM = 0; % no. of current measurment branch
NV = 0; % no. of vector fitting node
vfcplx_flag = 0;% flag of vector fitting complex node


% define the direction of the first condutor as reference direction
% cofLSign = sign(Lmtx(1:Nbran,1));


% off diagonal element
if Nbran > 1
    for ik = 1:Nbran-1
        fprintf(fid,'* *  Branch  %s - %s \n', nod_start_grid(ik,:), nod_end_grid(ik,:));
        
        for ig = ik+1:Nbran
            
            Nfit_grid = find(abs(Rvfit3(ik,ig,:))>err_fit, 1, 'last');
            Nfit_grid = min(Nfit_grid, find(abs(Lvfit3(ik,ig,:))>err_fit, 1, 'last'));
            %Rtmp = max(R0fit3(ik,ig), 1e-6);
            Rtmp = R0fit3(ik,ig);
            %nodR = ['nR_', num2str(ik)];
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
                NR, nod_start_grid(ik,:), NR, Rtmp*1e3);
            
            %% 2-a. with current measurment
            if bran_out_grid(ik) == 1
                
                % add current measurment block
                NM = NM+1;
                %nodM = ['nM_' num2str(ik)];
                fprintf(fid,'*  Mearsure Branch Current %s \n', bran_name_grid(ik,:));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, NR, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name_grid(ik,:), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name_grid(ik,:));
                %nodL1 = nodM;
                
                if Nfit_grid>0
                    % add vector fitting equivalent circuit
                    vfcplx_flag = Nfit_grid+1;
                    
                    for ih = 1:Nfit_grid
                        if ih == 1
                            NV = NV+1;
                            
                            if isreal(Rvfit3(ik,ig,ih))  % real pole
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rvfit3(ik,ig,ih));
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*Lvfit3(ik,ig,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rvfit3(ik,ig,ih);
                                R2 = Rvfit3(ik,ig,ih+1);
                                L1 = Lvfit3(ik,ig,ih);
                                L2 = Lvfit3(ik,ig,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*LC);
                            end
                        elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                            NV = NV+1;
                            
                            if isreal(Rvfit3(ik,ig,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rvfit3(ik,ig,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*Lvfit3(ik,ig,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rvfit3(ik,ig,ih);
                                R2 = Rvfit3(ik,ig,ih+1);
                                L1 = Lvfit3(ik,ig,ih);
                                L2 = Lvfit3(ik,ig,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                        end
                        
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end_grid(ig,:), 1e6*L0fit3(ik,ig));
                else
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                        NL, ik, nod_end_grid(ig,:), 1e6*L0fit3(ik,ig));
                end
                
                
                %% 2-b. no current measurment
            else
                if Nfit_grid>0
                    
                    vfcplx_flag = Nfit_grid+1;
                    
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit_grid
                        
                        if ih == 1
                            NV = NV+1;
                            
                            if isreal(Rvfit3(ik,ig,ih))  % real pole
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NR, NV, 1e3*Rvfit3(ik,ig,ih));
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                    NV, NR, NV, 1e6*Lvfit3(ik,ig,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rvfit3(ik,ig,ih);
                                R2 = Rvfit3(ik,ig,ih+1);
                                L1 = Lvfit3(ik,ig,ih);
                                L2 = Lvfit3(ik,ig,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NR, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NR, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                    NV, NR, NV, 1e6*LC);
                            end
                            
                        elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                            NV = NV+1;
                            
                            if isreal(Rvfit3(ik,ig,ih))  % real pole
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*Rvfit3(ik,ig,ih));
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*Lvfit3(ik,ig,ih));
                            else % complex pole
                                vfcplx_flag = ih+1;
                                
                                R1 = Rvfit3(ik,ig,ih);
                                R2 = Rvfit3(ik,ig,ih+1);
                                L1 = Lvfit3(ik,ig,ih);
                                L2 = Lvfit3(ik,ig,ih+1);
                                
                                LC = L1+L2;
                                RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                                RC1 = 1 / (1/(R1+R2)-1/RC2);
                                CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                                
                                fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC1);
                                fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                    NV, NV, NV, 1e6*CC);
                                fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NV-1, NV, 1e3*RC2);
                                fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                    NV, NV-1, NV, 1e6*LC);
                            end
                            
                        end
                    end
                    
                    %nodL1 = nodR;
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end_grid(ig,:), 1e6*L0fit3(ik,ig));
                else
                    
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                        NL, NR, nod_end_grid(ig,:), 1e6*L0fit3(ik,ig));
                end
                
            end
        end
    end
elseif Nbran==1
    %% R - 2-a, 2-b use the same R writing part
    
    Nfit_grid = find(abs(Rvfit3(ik,:))>err_fit, 1, 'last');
    
    fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', 1, nod_start_grid(1,:), 1, R0fit3(1,1)*1e3);
    
    %% 2-a. with current measurment
    if bran_out_grid(1) == 1
        
        % add current measurment block
        %nodM = ['nM_' num2str(ik)];
        fprintf(fid,'*  Mearsure Branch Current %s \n',bran_name_grid(1,:));
        % 0V Vdc
        fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', 1, 1, 1);
        % H (CCVS for measuring current)
        fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', 1, bran_name_grid(1,:), 1);
        fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', 1, bran_name_grid(1,:));
        %nodL1 = nodM;
        
        if Nfit_grid>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit_grid+1;
            
            for ih = 1:Nfit_grid
                
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rvfit3(ik,ih));
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*Lvfit3(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                    
                elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rvfit3(ik,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*Lvfit3(ik,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, NV, nod_end_grid(1,:), 1e6*Ls(1));
        else
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', NL, 1, nod_end_grid(1,:), 1e6*Ls(1));
            
        end
        %% 2-b. no current measurment
    else
        Nfit_grid = find(abs(Rvfit3(1,:))>err_fit, 1, 'last');
        %nodL1 = nodR;
        if Nfit_grid>0
            % add vector fitting equivalent circuit
            vfcplx_flag = Nfit_grid+1;
            
            for ih = 1:Nfit_grid
                if ih == 1
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*Rvfit3(1,ih));
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*Lvfit3(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, 1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                            NV, 1, NV, 1e6*LC);
                    end
                    
                elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                    NV = NV+1;
                    
                    if isreal(Rvfit3(ik,ih))  % real pole
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*Rvfit3(1,ih));
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*Lvfit3(1,ih));
                    else % complex pole
                        vfcplx_flag = ih+1;
                        
                        R1 = Rvfit3(ik,ih);
                        R2 = Rvfit3(ik,ih+1);
                        L1 = Lvfit3(ik,ih);
                        L2 = Lvfit3(ik,ih+1);
                        
                        LC = L1+L2;
                        RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                        RC1 = 1 / (1/(R1+R2)-1/RC2);
                        CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                        
                        fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC1);
                        fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                            NV, NV, NV, 1e6*CC);
                        fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                            NV, NV-1, NV, 1e3*RC2);
                        fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                            NV, NV-1, NV, 1e6*LC);
                    end
                end
            end
            
            % L
            fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, NV, nod_end_grid(1,:), 1e6*Ls(1));
        else
            
            fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', NL, 1, nod_end_grid(1,:), 1e6*Ls(1));
        end
    end
    
end


%% 3.b Write the GND node
% Adding nonlinear ground resistance modeling soil ionization effect
E0 = 350e3;  % E = 350kV/m
RGname =[fname_grid,'_Rion',];
NRG = 0;

if Nbran > 1
    for ik = 1:Nbran
        fprintf(fid,'* *  Node %s to ground \n', nod_start_grid(ik,:));
        
        Ig = 1/(2*pi)*E0*Rsoil/(Rgrod(ik)^2);
        
        Nfit_grid = find(abs(Rvfit3(ik,ik,:))>err_fit, 1, 'last');
        Nfit_grid = min(Nfit_grid, find(abs(Lvfit3(ik,ik,:))>err_fit, 1, 'last'));
        %nodR = ['nR_', num2str(ik)];
        NL = NL+1;
        NR = NR+1;
        fprintf(fid,'L_L%d  %s  nR_%d  %fuH \n', ...
            NL, nod_start_grid(ik,:), NR, L0fit3(ik,ik)*1e6);
        
        %% 2-a. with current measurment
        if bran_out_grid(ik) == 1
            
            % add current measurment block
            NM = NM+1;
            %nodM = ['nM_' num2str(ik)];
            fprintf(fid,'*  Mearsure Branch Current %s \n', bran_name_grid(ik,:));
            % 0V Vdc
            fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, NR, ik);
            % H (CCVS for measuring current)
            fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name_grid(ik,:), NM);
            fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name_grid(ik,:));
            %nodL1 = nodM;
            
            if Nfit_grid>0
                % add vector fitting equivalent circuit
                vfcplx_flag = Nfit_grid+1;
                
                for ih = 1:Nfit_grid
                    if ih == 1
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*Rvfit3(ik,ik,ih));
                            fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                NV, ik, NV, 1e6*Lvfit3(ik,ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ik,ih);
                            R2 = Rvfit3(ik,ik,ih+1);
                            L1 = Lvfit3(ik,ik,ih);
                            L2 = Lvfit3(ik,ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nM_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                NV, ik, NV, 1e6*LC);
                        end
                    elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rvfit3(ik,ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lvfit3(ik,ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ik,ih);
                            R2 = Rvfit3(ik,ik,ih+1);
                            L1 = Lvfit3(ik,ik,ih);
                            L2 = Lvfit3(ik,ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*LC);
                        end
                    end
                    
                end
                
                % L
%                 NL = NL+1;
%                 fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
%                     NL, NV, nod_end_grid(ig,:), 1e6*L0fit3(ik,ik));

                NRG = NRG+1;
                fprintf(fid,'X%d  nV_%d  %s PARAMS: Ig=%.2f  R0=%.4f \n', ...
                    NRG, NV, RGname, Ig, Rgrod(ik));
            else
                
                % L
%                 NL = NL+1;
%                 fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
%                     NL, ik, nod_end_grid(ig,:), 1e6*L0fit3(ik,ik));
                                
                NRG = NRG+1;
                fprintf(fid,'X%d  nM_%d  %s PARAMS: Ig=%.2f  R0=%.4f \n', ...
                    NRG, ik, RGname, Ig, Rgrod(ik));
            end
            
            
            %% 2-b. no current measurment
        else
            if Nfit_grid>0
                
                vfcplx_flag = Nfit_grid+1;
                
                % add vector fitting equivalent circuit
                for ih = 1:Nfit_grid
                    
                    if ih == 1
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NR, NV, 1e3*Rvfit3(ik,ik,ih));
                            fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                NV, NR, NV, 1e6*Lvfit3(ik,ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ik,ih);
                            R2 = Rvfit3(ik,ik,ih+1);
                            L1 = Lvfit3(ik,ik,ih);
                            L2 = Lvfit3(ik,ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nR_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                NV, NR, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NR, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                NV, NR, NV, 1e6*LC);
                        end
                        
                    elseif ih>1 && Nfit_grid>0 && ih~=vfcplx_flag
                        NV = NV+1;
                        
                        if isreal(Rvfit3(ik,ik,ih))  % real pole
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rvfit3(ik,ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lvfit3(ik,ik,ih));
                        else % complex pole
                            vfcplx_flag = ih+1;
                            
                            R1 = Rvfit3(ik,ik,ih);
                            R2 = Rvfit3(ik,ik,ih+1);
                            L1 = Lvfit3(ik,ik,ih);
                            L2 = Lvfit3(ik,ik,ih+1);
                            
                            LC = L1+L2;
                            RC2 = LC^2*R1*R2 / (R2*L1^2+R1*L2^2);
                            RC1 = 1 / (1/(R1+R2)-1/RC2);
                            CC = 1/RC1 * L1*L2/(R1*R2)*(R1+R2)/LC;
                            
                            fprintf(fid,'R_VC%d  nV_%d  nVC_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC1);
                            fprintf(fid,'C_V%d  nVC_%d  nV_%d  %fuF \n', ...
                                NV, NV, NV, 1e6*CC);
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*RC2);
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*LC);
                        end
                        
                    end
                end
                
                %nodL1 = nodR;
%                 NL = NL+1;
%                 fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
%                     NL, NV, nod_end_grid(ig,:), 1e6*L0fit3(ik,ig));
                
                NRG = NRG+1;
                fprintf(fid,'X%d  nV_%d  %s PARAMS: Ig=%.2f  R0=%.4f \n', ...
                    NRG, NV, RGname, Ig, Rgrod(ik));
            else
%                 NL = NL+1;
%                 fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
%                     NL, ik, nod_end_grid(ig,:), 1e6*L0fit3(ik,ig));
                
                NRG = NRG+1;
                fprintf(fid,'X%d  nR_%d  %s PARAMS: Ig=%.2f  R0=%.4f \n', ...
                    NRG, NR, RGname, Ig, Rgrod(ik));
            end
            
        end
    end
end


fprintf(fid,'.ENDS %s \n', fname_grid);

%% 4. Adding nonlinear ground resistance

fprintf(fid,'* Nonlinear Ground Resistance Used in Ground Grid\n');
fprintf(fid,'.SUBCKT  %s  1  PARAMS: Ig=1000  R0=20 \n', RGname);
fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
fprintf(fid,'V_I_SENSE  2  3  0V \n');
fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
fprintf(fid,'E_VAR  3  0 \n');
fprintf(fid,'+  VALUE={V(4)*{R0}/SQRT(1+ABS(V(4))/{Ig})} \n');
fprintf(fid,'.ENDS %s \n', RGname);

%% close the file after writing the spice file
fclose(fid);


end


