function spice_subckt_netlist_vf(Rmtx, Lmtx, Rfit, Lfit, Nfit, ...
    bran_type, bran_name, nod_start, nod_end, bran_output, nod_out, ...
    Nbran_out, Nnod_out, fpath, fname)
%  Function:       spice_subckt_netlist
%  Description:    Generate the spice netlist for built PEEC network.
%                  Vector fitting is added as in "Systematic development of
%                  transmission-line models for interconnects with
%                  frequency-dependent losses"
%                  1. header and output node
%                  2. network
%                        -  (1). self R + full L (R + 0Vdc + L)
%                              - (1).a  measurment branch  (R + 0Vdc + L )
%                              - (1).b  no measurment ( R + L )
%                        -  (2). self R + mutual R + full L
%                              (R + 0Vdc + E1+E2+...+ L)
%                              - (2).a  measurment branch (R + 0Vdc + E1+E2+...+ L)
%                              - (2).b  no measurment (R + E1+E2+...+ L)
%                  3. end of netlist
%  Calls:
%
%  Input:          Rmtx  --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lmtx  --  L matrix calculated using PEEC (N*N)(H)
%                  bran_name  --  branch name of all conductors
%                  bran_type  --  branch type of all conductors(measurmnt or not)
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  output     --  output node and branch name (measurment
%                                 of branch current will be transformed to
%                                 equivalent node voltage)
%                  Nbran      --  num. of branch
%                  Noutput    --  num. of output (all in node style)
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2014-12-24
%  History:

Rerr = 1e-6;
err_ML = 1e-3;
err_MR = 1e-6;
Nbran = size(Lmtx,1);
err_Rfit = 1e-6;
err_Lfit = 1e-10;

%% 1. Write the head of netlist (external port)
fid = fopen([fpath, fname,'.cir'],'w+');

fprintf(fid,'.SUBCKT %s ', fname);
% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
for ik = 1:Nnod_out
    fprintf(fid,'%s ',nod_out(ik,:));
    if mod(ik,5)==0 && ik~=Nnod_out
        fprintf(fid,'\n+ ');
    end
end

if Nnod_out>0 && Nbran_out>0
    fprintf(fid,'\n+ ');
end

for ik = 1:Nbran_out
    fprintf(fid,'%s ',bran_output(ik,:));
    if mod(ik,5)==0 && ik~=Nbran_out
        fprintf(fid,'\n+ ');
    end
end
fprintf(fid,'\n');

%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');


%% 3. Write Circuit Network
NR = 0;
NL = 0;
NK = 0;
NE = 0; % no. of added point for E (used for mutual R)
NM = 0; % no. of current measurment branch
NV = 0; % no. of vector fitting node

Ls = zeros(Nbran,1);
Ls(1:Nbran) = diag(Lmtx);

% define the direction of the first condutor as reference direction
%cofLSign = sign(Lmtx(1:Nbran,1));

cofK = zeros(Nbran,1);
cofMR = zeros(Nbran,1);

if Nbran > 1
    for ik = 1:Nbran
        
        idRsM = abs(Rmtx(ik+1:end,ik)) > 0;
        flgRm = sum(idRsM);
        
        fprintf(fid,'* *  Branch  %s - %s \n', nod_start(ik,:), nod_end(ik,:));
        
        %% 1. only full L  ( 0Vdc + L )
        if abs(Rmtx(ik,ik)) <= Rerr
            %% 1-a. with current measurment
            if bran_type(ik) == 1
                
                % add current measurment block
                NM = NM+1;
                %nodM = ['nM_', num2str(ik)];
                fprintf(fid,'*  Mearsure Branch Current %s \n',bran_name(ik,:));
                % 0V Vdc
                fprintf(fid,'V_M%d  %s  nM_%d  0Vdc \n', NM, nod_start(ik,:), ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name(ik,:), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name(ik,:));
                
                
                if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                NV, ik, NV, 1e6*Lfit(ik,ih));
                        elseif ih>1 && ...
                                (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lfit(ik,ih));
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, ...
                        NV, nod_end(ik,:), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                        NL, ik, nod_end(ik,:), 1e6*Ls(ik));
                end
                %% 1-b. no current measurment
            else
                
                if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            fprintf(fid,'R_V%d  %s  nV_%d  %fm  TC=0,0 \n', ...
                                NV, nod_start(ik,:), NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  %s  nV_%d  %fuH \n', ...
                                NV, nod_start(ik,:), NV, 1e6*Lfit(ik,ih));
                        elseif ih>1 && (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lfit(ik,ih));
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end(ik,:), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  %s  %s  %fuH \n', ...
                        NL, nod_start(ik,:), nod_end(ik,:), 1e6*Ls(ik));
                    
                end
            end
            
            %% K -- 1-a, 1-b use the same K writing part
            cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
                end
            end
            
            %% 2. self R + full L (R + 0Vdc + L)
        elseif abs(Rmtx(ik,ik))>Rerr && flgRm==0
            
            %% R - 2-a, 2-b use the same R writing part
            %nodR = ['nR_', num2str(ik)];
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
                NR, nod_start(ik,:), ik, Rmtx(ik,ik)*1e3);
            
            %% 2-a. with current measurment
            if bran_type(ik) == 1
                
                % add current measurment block
                NM = NM+1;
                %nodM = ['nM_' num2str(ik)];
                fprintf(fid,'*  Mearsure Branch Current %s \n', bran_name(ik,:));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name(ik,:), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name(ik,:));
                %nodL1 = nodM;
                
                if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                NV, ik, NV, 1e6*Lfit(ik,ih));
                        elseif ih>1 && (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lfit(ik,ih));
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end(ik,:), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                        NL, ik, nod_end(ik,:), 1e6*Ls(ik));
                end
                
                
                
                %% 2-b. no current measurment
            else
                if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, ik, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                NV, ik, NV, 1e6*Lfit(ik,ih));
                        elseif ih>1 && (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lfit(ik,ih));
                        end
                    end
                    
                    %nodL1 = nodR;
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end(ik,:), 1e6*Ls(ik));
                else
                    
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                        NL, ik, nod_end(ik,:), 1e6*Ls(ik));
                end
                
            end
            
            %% K -- 2-a, 2-b use the same K writing part
            cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
                end
            end
            
            
            %% 3. self R + mutual R + full L (R + 0Vdc + E1+E2+...+ L)
        elseif abs(Rmtx(ik,ik))>Rerr && flgRm>0
            
            %% R -- 3-a, 3-b use the same R writing part
            %nodR = ['nR_', num2str(ik)];
            NR = NR+1;
            fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
                NR, nod_start(ik,:), ik, Rmtx(ik,ik)*1e3);
            
            %% 3-a. with current measurment (R + 0Vdc + E1+E2+...+ L)
            if bran_type(ik) == 1  %
                
                % add current measurment block
                %nodM = ['nM_', num2str(ik)];
                NM = NM+1;
                fprintf(fid,'*  Mearsure Branch Current %s \n',bran_name(ik,:));
                % 0V Vdc
                fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
                % H (CCVS for measuring current)
                fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name(ik,:), NM);
                fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name(ik,:));
                
                %nodE0 = nodM;   % first node of E series (mutual R)
                %nodE2 = nodE0;  % initial nodE2 for case of no E exist
                
                % E - mutual R (VCVS)
                cofMR(1:Nbran) = Rmtx(1:Nbran,ik)./Rmtx(ik,ik);
                cofMR(ik) = 0;
                idRsM = find(abs(cofMR) > err_MR);
                NMR = length(idRsM);
                
                for ih = 1:NMR
                    %nodRex = ['nR_', num2str(ind(ih))];
                    if ih==1 && ih~=ik % first node is set to be nodE0
                        NE = NE+1;
                        %nodE1 = ['nE_', num2str(NE)];
                        %nodE2 = nodE1;
                        fprintf(fid,'E_E%d  nM_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE, ik, NE, nod_start(idRsM(ih),:), idRsM(ih), cofMR(idRsM(ih)));
                    elseif ih>1 && ih~=ik
                        NE = NE+1;
                        %nodE1 = ['nE_', num2str(NE-1)];
                        %nodE2 = ['nE_', num2str(NE)];
                        fprintf(fid,'E_E%d  nE_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE,  NE-1, NE, nod_start(idRsM(ih),:), idRsM(ih), cofMR(idRsM(ih)));
                    end
                end
                
                if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            if NMR == 0
                                fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*Lfit(ik,ih));
                            elseif NMR >= 1
                                fprintf(fid,'R_V%d  nE_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NE, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nE_%d  nV_%d  %fuH \n', ...
                                    NV, NE, NV, 1e6*Lfit(ik,ih));
                            end
                        elseif ih>1 && (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lfit(ik,ih));
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end(ik,:), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    if NMR == 0
                        fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                            NL, ik, nod_end(ik,:), 1e6*Ls(ik));
                    elseif NMR >= 1
                        fprintf(fid,'L_L%d  nE_%d  %s  %fuH \n', ...
                            NL, NE, nod_end(ik,:), 1e6*Ls(ik));
                    end
                end
                %% 3-b. no current measurment (R + E1+E2+...+ L)
            else
                %nodE0 = nodR;   % first node of E series (mutual R)
                %nodE2 = nodE0;  % initial nodE2 for case of no E exist
                
                % E - mutual R (VCVS)
                cofMR(1:Nbran) = Rmtx(1:Nbran,ik)./Rmtx(ik,ik);
                cofMR(ik) = 0;
                idRsM = find(abs(cofMR) > err_MR);
                NMR = length(idRsM);
                
                for ih = 1:NMR
                    if ih==1 && ih~=ik % first node is set to be nodE0
                        NE = NE+1;
                        fprintf(fid,'E_E%d  nR_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE, ik, NE, nod_start(idRsM(ih),:), idRsM(ih), cofMR(idRsM(ih)));
                    elseif ih>1 && ih~=ik
                        NE = NE+1;
                        fprintf(fid,'E_E%d  nE_%d  nE_%d  %s  nR_%d  %f \n', ...
                            NE, NE-1, NE, nod_start(idRsM(ih),:), idRsM(ih), cofMR(idRsM(ih)));
                    end
                end
                
                if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
                    % add vector fitting equivalent circuit
                    for ih = 1:Nfit
                        if ih == 1
                            NV = NV+1;
                            if NMR == 0
                                fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, ik, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                                    NV, ik, NV, 1e6*Lfit(ik,ih));
                            elseif NMR >= 1
                                fprintf(fid,'R_V%d  nE_%d  nV_%d  %fm  TC=0,0 \n', ...
                                    NV, NE, NV, 1e3*Rfit(ik,ih));
                                fprintf(fid,'L_V%d  nE_%d  nV_%d  %fuH \n', ...
                                    NV, NE, NV, 1e6*Lfit(ik,ih));
                            end
                        elseif ih>1 && (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                            NV = NV+1;
                            fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                                NV, NV-1, NV, 1e3*Rfit(ik,ih));
                            fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                                NV, NV-1, NV, 1e6*Lfit(ik,ih));
                        end
                    end
                    
                    % L
                    NL = NL+1;
                    fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', ...
                        NL, NV, nod_end(ik,:), 1e6*Ls(ik));
                else
                    
                    % L
                    NL = NL+1;
                    if NMR == 0
                        fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                            NL, ik, nod_end(ik,:), 1e6*Ls(ik));
                    elseif NMR >= 1
                        fprintf(fid,'L_L%d  nE_%d  %s  %fuH \n', ...
                            NL, NE, nod_end(ik,:), 1e6*Ls(ik));
                    end
                end
            end
            
            %% K -- 3-a, 3-b use the same K writing part
            cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
            for ih = ik+1:Nbran
                if cofK(ih) > 1
                    cofK(ih) = 0.99;
                elseif cofK(ih) < -1
                    cofK(ih) = -0.99;
                end
                
                if abs(cofK(ih)) > err_ML
                    NK = NK+1;
                    fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                        NK, ik, ih, cofK(ih));
                end
            end
        end
    end
    
elseif Nbran==1
    %% R - 2-a, 2-b use the same R writing part
    fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', 1, nod_start(1,:), 1, Rmtx(1,1)*1e3);
    
    %% 2-a. with current measurment
    if bran_type(1) == 1
        
        % add current measurment block
        %nodM = ['nM_' num2str(ik)];
        fprintf(fid,'*  Mearsure Branch Current %s \n',bran_name(1,:));
        % 0V Vdc
        fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', 1, 1, 1);
        % H (CCVS for measuring current)
        fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', 1, bran_name(1,:), 1);
        fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', 1, bran_name(1,:));
        %nodL1 = nodM;
        
        if abs(Rfit(ik,1))>err_Rfit || abs(Lfit(ik,1))>err_Lfit
            % add vector fitting equivalent circuit
            for ih = 1:Nfit
                if ih == 1
                    NV = NV+1;
                    fprintf(fid,'R_V%d  nM_%d  nV_%d  %fm  TC=0,0 \n', ...
                        NV, 1, NV, 1e3*Rfit(ik,ih));
                    fprintf(fid,'L_V%d  nM_%d  nV_%d  %fuH \n', ...
                        NV, 1, NV, 1e6*Lfit(ik,ih));
                elseif ih>1 && (abs(Rfit(ik,ih))>err_Rfit || abs(Lfit(ik,ih))>err_Lfit)
                    NV = NV+1;
                    fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                        NV, NV-1, NV, 1e3*Rfit(ik,ih));
                    fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                        NV, NV-1, NV, 1e6*Lfit(ik,ih));
                end
            end
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, NV, nod_end(1,:), 1e6*Ls(1));
        else
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', NL, 1, nod_end(1,:), 1e6*Ls(1));
            
        end
        %% 2-b. no current measurment
    else
        %nodL1 = nodR;
        if abs(Rfit(1,1))>err_Rfit || abs(Lfit(1,1))>err_Lfit
            % add vector fitting equivalent circuit
            for ih = 1:Nfit
                if ih == 1
                    NV = NV+1;
                    fprintf(fid,'R_V%d  nR_%d  nV_%d  %fm  TC=0,0 \n', ...
                        NV, 1, NV, 1e3*Rfit(1,ih));
                    fprintf(fid,'L_V%d  nR_%d  nV_%d  %fuH \n', ...
                        NV, 1, NV, 1e6*Lfit(1,ih));
                elseif ih>1 && (abs(Rfit(1,ih))>err_Rfit || abs(Lfit(1,ih))>err_Lfit)
                    NV = NV+1;
                    fprintf(fid,'R_V%d  nV_%d  nV_%d  %fm  TC=0,0 \n', ...
                        NV, NV-1, NV, 1e3*Rfit(1,ih));
                    fprintf(fid,'L_V%d  nV_%d  nV_%d  %fuH \n', ...
                        NV, NV-1, NV, 1e6*Lfit(1,ih));
                end
            end
            
            % L
            fprintf(fid,'L_L%d  nV_%d  %s  %fuH \n', NL, NV, nod_end(1,:), 1e6*Ls(1));
        else
            
            fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', NL, 1, nod_end(1,:), 1e6*Ls(1));
        end
    end
    
end


%% Adding file End
fprintf(fid,'.ENDS %s \n', fname);

fclose(fid);


end


