function spice_grid_y_na(Rmtx,Lmtx,Rgrid,Cgrid, ...
    bran_name_grid,nod_start_grid,nod_end_grid, ...
    bran_out_grid,nod_out_grid, Rsoil,fpath_grid,fname_grid)
%  Function:       spice_grid_y_na
%  Description:    Generate the spice netlist for built ground grid network.
%                  1. header and output node
%                  2. network
%                        -  2. self R + full L (R + 0Vdc + L)
%                              - 1.b  no measurment ( R + L )
%
%                  3. nod_gnd connect to nonlinear ground resistance
%                  4. ground resistance netlist
%  Calls:
%
%  Input:          Rgrid --  R matrix calculated using PEEC (N*N)(ohm)
%                  Lgrid --  L matrix calculated using PEEC (N*N)(H)
%                  nod_start  --  start node name of all conductors
%                  nod_end    --  end node name of all conductors
%                  nod_output --  output node and branch name (measurment
%                                 of branch current will be transformed to
%                                 equivalent node voltage)
%                  nod_gnd    --  ground node (connect to nonlinear Rg)
%                  Nnod_out   --  num. of output (all in node style)
%                  Nnod_gnd   --  num. of ground node (all in node style)
%                  cond_soil  --  conductivity of soil
%                  Rsoil      --  resistance of soil
%                  fpath      --  path for saving .cir file
%                  fname      --  name for saving .cir file
%  Output:         netlist file (*.cir)
%  Others:
%  Author:         Chen Hongcai
%  Email :         hc.chen@live.com
%  Date:           2015-4-22
%  History:


err_ML = 1e-3;

Rmtx = full(Rmtx);
Lmtx = full(Lmtx);
Rgrid = full(Rgrid);
Cgrid = full(Cgrid);


Nbran     = size(Lmtx,1);
Nbran_out_grid = size(bran_out_grid,1);
Nnod_out_grid  = size(nod_out_grid,1);

fname_grid = [fname_grid,'_grid'];

%% Write the head of netlist (external port)
fid = fopen([fpath_grid, fname_grid,'.cir'],'w+');

% external port of subckt
% measuring branch current, measuring node voltage, external connecting node
fprintf(fid,'.SUBCKT %s ',fname_grid);

for ik = 1:Nnod_out_grid
    fprintf(fid,'%s ',nod_out_grid(ik,:));
    if mod(ik,5)==0 && ik~=Nnod_out_grid
        fprintf(fid,'\n+ ');
    end
end

if Nnod_out_grid>0 && Nbran_out_grid>0
    fprintf(fid,'\n+ ');
end

for ik = 1:Nbran_out_grid
    fprintf(fid,'%s ',bran_out_grid(ik,:));
    if mod(ik,5)==0 && ik~=Nbran_out_grid
        fprintf(fid,'\n+ ');
    end
end
fprintf(fid,'\n');


%% 2. Description
fprintf(fid,'************************************** \n');
fprintf(fid,'*   Model Generated by Chen Hongcai  * \n');
fprintf(fid,'*   Hong Kong Polytechic University  * \n');
fprintf(fid,'*         All Rights Reserved        * \n');
fprintf(fid,'*       Email:  hc.chen@live.com     * \n');
fprintf(fid,'************************************** \n');
fprintf(fid,'* Model generated on %s \n',datestr(now,1));
fprintf(fid,'* MODEL FORMAT: PSpice \n');

%% 3.a Write the R+L of Circuit Network
NR = 0;
NL = 0;
NK = 0;

Ls = zeros(Nbran,1);
Ls(1:Nbran) = diag(Lmtx);

cofK = zeros(Nbran,1);

if Nbran > 1
    for ik = 1:Nbran
        
        nod_mid = ['NMID',num2str(ik,'%.10d')];
        fprintf(fid,'* *  Ground Grid (%s - %s - %s)\n', ...
            nod_start_grid(ik,:),nod_mid, nod_end_grid(ik,:));
        
        %% (1). self R + full L (R + 0Vdc + L)
        % R
        Rtmp = max(Rmtx(ik,ik), 1e-6);
        %nodR = ['nR_', num2string(ik)];
        NR = NR+1;
        fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0\n', ...
            NR, nod_start_grid(ik,:), ik, Rtmp*1e3/2);
        
        %% 2-a. with current measurment
        if ~isempty(bran_out_grid) && ...
                ismember(bran_name_grid(ik,:),bran_out_grid,'rows')
            
            % add current measurment block
            NM = NM+1;
            %nodM = ['nM_' num2str(ik)];
            fprintf(fid,'*  Mearsure Branch Current %s \n', bran_name_grid(ik,:));
            % 0V Vdc
            fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', NM, ik, ik);
            % H (CCVS for measuring current)
            fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', NM, bran_name_grid(ik,:), NM);
            fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', NM, bran_name_grid(ik,:));
            %nodL1 = nodM;
            
            % L
            NL = NL+1;
            fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', ...
                NL, ik, nod_mid, 1e6*Ls(ik)/2);
            
            %% 2-b. no current measurment
        else
            %nodL1 = nodR;
            NL = NL+1;
            fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
                NL, ik, nod_mid, 1e6*Ls(ik)/2);
        end
        
        %% K -- 2-a, 2-b use the same K writing part
        cofK(ik+1:Nbran) = Lmtx(ik+1:Nbran,ik)./sqrt(Ls(ik).*Ls(ik+1:Nbran));
        for ih = ik+1:Nbran
            if cofK(ih) >= 1
                cofK(ih) = 0.9999;
            elseif cofK(ih) <= -1
                cofK(ih) = -0.9999;
            end
            
            if abs(cofK(ih)) > err_ML
                NK = NK+1;
                fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', NK, ik, ih, cofK(ih));
            end
        end
        
        % % % % % %
        fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0\n', ...
            NR+Nbran, nod_mid, ik+Nbran, Rtmp*1e3/2);
        fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
            NL+Nbran, ik+Nbran, nod_end_grid(ik,:), 1e6*Ls(ik)/2);
        
        for ih = ik+1:Nbran
            if abs(cofK(ih)) > err_ML
                NK = NK+1;
                fprintf(fid,'K_K%d  L_L%d  L_L%d  %.4f \n', ...
                    NK, ik+Nbran, ih+Nbran, cofK(ih));
            end
        end
    end
    
elseif Nbran==1
    
    nod_mid = ['NMID',num2str(1,'%.10d')];
    
    fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
        1, nod_start_grid(1,:), 1, Rmtx(1,1)*1e3/2);
    
    %% 2-a. with current measurment
    if ~isempty(bran_out_grid) && ...
            ismember(bran_name_grid(1,:),bran_out_grid,'rows')
        
        % add current measurment block
        %nodM = ['nM_' num2str(ik)];
        fprintf(fid,'*  Mearsure Branch Current %s \n',bran_name_grid(1,:));
        % 0V Vdc
        fprintf(fid,'V_M%d  nR_%d  nM_%d  0Vdc \n', 1, 1, 1);
        % H (CCVS for measuring current)
        fprintf(fid,'H_M%d  %s  0  V_M%d  1 \n', 1, bran_name_grid(1,:), 1);
        fprintf(fid,'R_M%d  %s  0  1G  TC=0,0 \n', 1, bran_name_grid(1,:));
        %nodL1 = nodM;
        
        % L
        fprintf(fid,'L_L%d  nM_%d  %s  %fuH \n', 1, 1, nod_mid, 1e6*Ls(1)/2);
        
        %% 2-b. no current measurment
    else
        %nodL1 = nodR;
        fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', 1, 1, nod_mid, 1e6*Ls(1)/2);
    end
    
    % % % % %
    fprintf(fid,'R_R%d  %s  nR_%d  %fm  TC=0,0 \n', ...
        2, nod_mid, 2, Rmtx(1,1)*1e3/2);
    fprintf(fid,'L_L%d  nR_%d  %s  %fuH \n', ...
        2, 2, nod_end_grid(1,:), 1e6*Ls(1)/2);
end

%% 3.b Write mutual capacitance
for ik = 1:Nbran-1
    for ig = ik+1:Nbran
        fprintf(fid,'R_RM%d  %s  %s  %fm  TC=0,0 \n', ...
            ik, nod_start_grid(ik,:), nod_end_grid(ig,:), Rgrid(ik,ig)*1e3);
        fprintf(fid,'C_CM%d  %s  %s  %fpF \n', ...
            ik, nod_start_grid(ik,:), nod_end_grid(ig,:), Cgrid(ik,ig)*1e9);
    end
end

%% 3.c Write the GND node
% Adding nonlinear ground resistance
E0 = 400e3;  % 400kV
RGname =[fname_grid,'_Rrod',];
NRG = 0;
for ik = 1:Nbran
    Ig = 1/(2*pi)*E0*Rsoil/(Rgrid(ik,ik)^2);
    
    nod_mid = ['NMID',num2str(ik,'%.10d')];
    fprintf(fid,'*  Ground rod %d - %s \n', ik, nod_mid);
    
    NRG = NRG+1;
    fprintf(fid,'X%d  %s  %s PARAMS: Ig=%.2f \n', ...
        NRG, nod_mid, RGname, Ig);
end

fprintf(fid,'.ENDS %s \n', fname_grid);

%% 4. Adding nonlinear ground resistance

fprintf(fid,'* Nonlinear Ground Resistance Used in Ground Grid\n');
fprintf(fid,'.SUBCKT  %s  1  PARAMS: Ig=1000 \n', RGname);
fprintf(fid,'R_R_ROD    1  2  1u  TC=0,0 \n');
fprintf(fid,'V_I_SENSE  2  3  0V \n');
fprintf(fid,'H_I_SENSE  4  0  V_I_SENSE   1 \n');
fprintf(fid,'R_I_SENSE  4  0  1G   TC=0,0 \n');
fprintf(fid,'E_VAR  3  0 \n');
fprintf(fid,'+  VALUE={V(4)*%.4f/SQRT(1+ABS(V(4))/{Ig})} \n', Rsoil);
fprintf(fid,'.ENDS %s \n', RGname);

%% close the file after writing the spice file
fclose(fid);

end


